INFO 12/23/202212:51:33 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202212:51:33 AM logging in using static token
INFO 12/23/202212:51:34 AM Shard ID None has connected to Gateway (Session ID: 1078e2c5daf63ba8ceb632496995f3c1).
INFO 12/23/202212:51:36 AM Logged on as "Der Volksempfänger#5892"
INFO 12/23/202212:52:18 AM Connecting to voice...
INFO 12/23/202212:52:18 AM Starting voice handshake... (connection attempt 1)
INFO 12/23/202212:52:18 AM Voice handshake complete. Endpoint found frankfurt487.discord.media
INFO 12/23/202212:52:19 AM New Instance opened at "Test Discord"
INFO 12/23/202212:52:19 AM "Test Discord": Request "last christmas"
INFO 12/23/202212:52:22 AM "Test Discord": Request "Wham! - Last Christmas (Lyrics)" took 3s!
INFO 12/23/202212:52:22 AM "Test Discord": Playing position 0: https://youtu.be/FC1xntc5KJs Wham! - Last Christmas (Lyrics)
WARNING 12/23/202212:56:46 AM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 12/23/202212:56:46 AM ffmpeg process 14040 successfully terminated with return code of 0.
INFO 12/23/202201:04:51 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 12/23/202201:04:52 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202201:04:52 AM logging in using static token
INFO 12/23/202201:04:53 AM Shard ID None has connected to Gateway (Session ID: a2d8a984f3c61489b43cc81ca40a0c52).
INFO 12/23/202201:04:55 AM Logged on as "Der Volksempfänger#5892"
INFO 12/23/202201:04:59 AM Connecting to voice...
INFO 12/23/202201:04:59 AM Starting voice handshake... (connection attempt 1)
INFO 12/23/202201:05:00 AM Voice handshake complete. Endpoint found frankfurt487.discord.media
INFO 12/23/202201:05:00 AM New Instance opened at "Test Discord"
INFO 12/23/202201:05:00 AM "Test Discord": Request "20 second long video"
WARNING 12/23/202201:05:28 AM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 12/23/202201:05:28 AM ffmpeg process 16056 successfully terminated with return code of 0.
INFO 12/23/202201:08:11 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 12/23/202201:08:12 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202201:08:12 AM logging in using static token
INFO 12/23/202201:08:13 AM Shard ID None has connected to Gateway (Session ID: 82fb195ca067bc645fb64c4a45ce3f8d).
INFO 12/23/202201:08:15 AM Logged on as "Der Volksempfänger#5892"
INFO 12/23/202201:08:18 AM Connecting to voice...
INFO 12/23/202201:08:18 AM Starting voice handshake... (connection attempt 1)
INFO 12/23/202201:08:18 AM Voice handshake complete. Endpoint found frankfurt487.discord.media
INFO 12/23/202201:08:18 AM New Instance opened at "Test Discord"
INFO 12/23/202201:08:18 AM "Test Discord": Request "20 second long video"
INFO 12/23/202201:08:21 AM "Test Discord": Request "b'20 SECOND TIMER '" took 2s!
WARNING 12/23/202201:08:47 AM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 12/23/202201:08:47 AM ffmpeg process 20324 successfully terminated with return code of 0.
INFO 12/23/202201:08:53 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 12/23/202201:08:53 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202201:08:53 AM logging in using static token
INFO 12/23/202201:08:54 AM Shard ID None has connected to Gateway (Session ID: e94963c4e9406505bfe66e4104ca1cde).
INFO 12/23/202201:08:56 AM Logged on as "Der Volksempfänger#5892"
INFO 12/23/202201:09:00 AM Connecting to voice...
INFO 12/23/202201:09:00 AM Starting voice handshake... (connection attempt 1)
INFO 12/23/202201:09:00 AM Voice handshake complete. Endpoint found frankfurt487.discord.media
INFO 12/23/202201:09:00 AM New Instance opened at "Test Discord"
INFO 12/23/202201:09:00 AM "Test Discord": Request "20 second long video"
INFO 12/23/202201:09:02 AM "Test Discord": Request "b'20 SECOND TIMER '" took 1s!
WARNING 12/23/202201:09:28 AM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 12/23/202201:09:28 AM ffmpeg process 2080 successfully terminated with return code of 0.
INFO 12/23/202201:09:46 AM "Test Discord": Request "10 second long video"
INFO 12/23/202201:09:48 AM "Test Discord": Request "b'10 hours and 1 second of pure black screen!'" took 1s!
ERROR 12/23/202201:10:08 AM Probe 'native' using 'ffmpeg' failed, trying fallback
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 526, in probe
    codec, bitrate = await loop.run_in_executor(None, lambda: probefunc(source, executable))
  File "C:\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 526, in <lambda>
    codec, bitrate = await loop.run_in_executor(None, lambda: probefunc(source, executable))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 548, in _probe_codec_native
    output = subprocess.check_output(args, timeout=20)
  File "C:\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python39\lib\subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Python39\lib\subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python39\lib\subprocess.py", line 1510, in _communicate
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_streams', '-select_streams', 'a:0', 'https://rr5---sn-i5h7lnl6.googlevideo.com/videoplayback?expire=1671775787&ei=y_GkY8m9E877xN8P6_yjqAo&ip=2a02%3A8108%3A83c0%3A1097%3A51cd%3Ac75a%3A28ac%3A74bb&id=o-AO_sooHxgH11d2v5mvuls6RKb0k-1P-wWjnDQ3GEMLoW&itag=251&source=youtube&requiressl=yes&mh=_o&mm=31%2C26&mn=sn-i5h7lnl6%2Csn-4g5lznle&ms=au%2Conr&mv=m&mvi=5&pl=50&initcwndbps=2528750&spc=zIddbOZsI8uMq5uMXRWZB6Y7Dq-w_TE&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=16304969&dur=36000.061&lmt=1648950511497172&mt=1671753684&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAM4WMW7GSe-lGC20-HT8FmD1qZjTohGoVh0OcNUU3I9lAiApbfwxCoWAOqUFQvKzMV8wo4VkqeMP7sAnw7-4-hTHeg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgU3P6z3HhyXnWzVDCiYS3LqNXSGNFRdW9nlbVqWcGyacCIHH0VzCVDhDXoGlyquRDjCG-W-OP-l3MH6FaYhJoo2n1']' timed out after 20 seconds
ERROR 12/23/202201:10:28 AM Fallback probe using 'ffmpeg' failed
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 526, in probe
    codec, bitrate = await loop.run_in_executor(None, lambda: probefunc(source, executable))
  File "C:\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 526, in <lambda>
    codec, bitrate = await loop.run_in_executor(None, lambda: probefunc(source, executable))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 548, in _probe_codec_native
    output = subprocess.check_output(args, timeout=20)
  File "C:\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python39\lib\subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Python39\lib\subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python39\lib\subprocess.py", line 1510, in _communicate
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_streams', '-select_streams', 'a:0', 'https://rr5---sn-i5h7lnl6.googlevideo.com/videoplayback?expire=1671775787&ei=y_GkY8m9E877xN8P6_yjqAo&ip=2a02%3A8108%3A83c0%3A1097%3A51cd%3Ac75a%3A28ac%3A74bb&id=o-AO_sooHxgH11d2v5mvuls6RKb0k-1P-wWjnDQ3GEMLoW&itag=251&source=youtube&requiressl=yes&mh=_o&mm=31%2C26&mn=sn-i5h7lnl6%2Csn-4g5lznle&ms=au%2Conr&mv=m&mvi=5&pl=50&initcwndbps=2528750&spc=zIddbOZsI8uMq5uMXRWZB6Y7Dq-w_TE&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=16304969&dur=36000.061&lmt=1648950511497172&mt=1671753684&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAM4WMW7GSe-lGC20-HT8FmD1qZjTohGoVh0OcNUU3I9lAiApbfwxCoWAOqUFQvKzMV8wo4VkqeMP7sAnw7-4-hTHeg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgU3P6z3HhyXnWzVDCiYS3LqNXSGNFRdW9nlbVqWcGyacCIHH0VzCVDhDXoGlyquRDjCG-W-OP-l3MH6FaYhJoo2n1']' timed out after 20 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 534, in probe
    codec, bitrate = await loop.run_in_executor(None, lambda: fallback(source, executable))
  File "C:\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 534, in <lambda>
    codec, bitrate = await loop.run_in_executor(None, lambda: fallback(source, executable))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 565, in _probe_codec_fallback
    out, _ = proc.communicate(timeout=20)
  File "C:\Python39\lib\subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python39\lib\subprocess.py", line 1510, in _communicate
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['ffmpeg', '-hide_banner', '-i', 'https://rr5---sn-i5h7lnl6.googlevideo.com/videoplayback?expire=1671775787&ei=y_GkY8m9E877xN8P6_yjqAo&ip=2a02%3A8108%3A83c0%3A1097%3A51cd%3Ac75a%3A28ac%3A74bb&id=o-AO_sooHxgH11d2v5mvuls6RKb0k-1P-wWjnDQ3GEMLoW&itag=251&source=youtube&requiressl=yes&mh=_o&mm=31%2C26&mn=sn-i5h7lnl6%2Csn-4g5lznle&ms=au%2Conr&mv=m&mvi=5&pl=50&initcwndbps=2528750&spc=zIddbOZsI8uMq5uMXRWZB6Y7Dq-w_TE&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=16304969&dur=36000.061&lmt=1648950511497172&mt=1671753684&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAM4WMW7GSe-lGC20-HT8FmD1qZjTohGoVh0OcNUU3I9lAiApbfwxCoWAOqUFQvKzMV8wo4VkqeMP7sAnw7-4-hTHeg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgU3P6z3HhyXnWzVDCiYS3LqNXSGNFRdW9nlbVqWcGyacCIHH0VzCVDhDXoGlyquRDjCG-W-OP-l3MH6FaYhJoo2n1']' timed out after 20 seconds
ERROR 12/23/202201:11:24 AM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 90, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 102, in song_complete
    file = random.choice(os.listdir(projectDir + "ads/"))
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\revol\\Documents\\Projects\\Python\\ve-pyads/'
INFO 12/23/202201:11:24 AM ffmpeg process 11472 has not terminated. Waiting to terminate...
INFO 12/23/202201:11:24 AM ffmpeg process 11472 should have terminated with a return code of 1.
INFO 12/23/202201:11:24 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 12/23/202201:11:24 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202201:11:24 AM logging in using static token
INFO 12/23/202201:11:25 AM Shard ID None has connected to Gateway (Session ID: b46fcca7f256c9cea1419fe3b46bebba).
INFO 12/23/202201:11:27 AM Logged on as "Der Volksempfänger#5892"
INFO 12/23/202201:11:29 AM Connecting to voice...
INFO 12/23/202201:11:29 AM Starting voice handshake... (connection attempt 1)
INFO 12/23/202201:11:30 AM Voice handshake complete. Endpoint found frankfurt487.discord.media
INFO 12/23/202201:11:30 AM New Instance opened at "Test Discord"
INFO 12/23/202201:11:30 AM "Test Discord": Request "10 second long video"
INFO 12/23/202201:11:32 AM "Test Discord": Request "b'10 Second Interval Timer'" took 2s!
ERROR 12/23/202201:12:21 AM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 90, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 102, in song_complete
    file = random.choice(os.listdir(projectDir + "ads/"))
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\revol\\Documents\\Projects\\Python\\ve-pyads/'
INFO 12/23/202201:12:21 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 12/23/202201:12:21 AM ffmpeg process 20464 has not terminated. Waiting to terminate...
INFO 12/23/202201:12:21 AM ffmpeg process 20464 should have terminated with a return code of 1.
INFO 12/23/202201:12:40 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202201:12:40 AM logging in using static token
INFO 12/23/202201:12:40 AM Shard ID None has connected to Gateway (Session ID: 22ed91108a99fd21c5fdb063091d5244).
INFO 12/23/202201:12:54 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202201:12:54 AM logging in using static token
INFO 12/23/202201:12:55 AM Shard ID None has connected to Gateway (Session ID: 80ffdf9544eae7afc2c92cd4000e971e).
INFO 12/23/202201:12:57 AM Logged on as "Der Volksempfänger#5892"
INFO 12/23/202201:12:59 AM Connecting to voice...
INFO 12/23/202201:12:59 AM Starting voice handshake... (connection attempt 1)
INFO 12/23/202201:12:59 AM Voice handshake complete. Endpoint found frankfurt487.discord.media
INFO 12/23/202201:13:00 AM New Instance opened at "Test Discord"
INFO 12/23/202201:13:00 AM "Test Discord": Request "10 second long video"
INFO 12/23/202201:13:02 AM "Test Discord": Request "b'10 hours and 1 second of pure black screen!'" took 2s!
ERROR 12/23/202201:13:22 AM Probe 'native' using 'ffmpeg' failed, trying fallback
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 526, in probe
    codec, bitrate = await loop.run_in_executor(None, lambda: probefunc(source, executable))
  File "C:\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 526, in <lambda>
    codec, bitrate = await loop.run_in_executor(None, lambda: probefunc(source, executable))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 548, in _probe_codec_native
    output = subprocess.check_output(args, timeout=20)
  File "C:\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python39\lib\subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Python39\lib\subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python39\lib\subprocess.py", line 1510, in _communicate
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_streams', '-select_streams', 'a:0', 'https://rr5---sn-i5h7lnl6.googlevideo.com/videoplayback?expire=1671775981&ei=jfKkY4-wDvSgvdIPqZOP0A4&ip=2a02%3A8108%3A83c0%3A1097%3A51cd%3Ac75a%3A28ac%3A74bb&id=o-AK4NE4mhJNlrCEYucvpxRdDvlTtnRntvsJM3a3sp2jer&itag=251&source=youtube&requiressl=yes&mh=_o&mm=31%2C26&mn=sn-i5h7lnl6%2Csn-4g5edn6k&ms=au%2Conr&mv=m&mvi=5&pl=50&initcwndbps=2587500&spc=zIddbPxcY6BESfqoYRSzTBph_SnAMRs&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=16304969&dur=36000.061&lmt=1648950511497172&mt=1671754170&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANYBYOCO3RzAYCqqEpEz-m1GBIr9GfomfhWDQxSBuwxvAiEA8LhhbHG6gFuiUMWnebHtqAuQABFNyrBR4Tf2d9gdDgQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgTLmHMjTwWG0iWe-MleXXYFoJx13q1ZVpISNRlFzKZb8CIQCyJarY22Y1DNlnywQ_tEREk1RkycjzJh5rJwZtbHeoSg%3D%3D']' timed out after 20 seconds
ERROR 12/23/202201:13:42 AM Fallback probe using 'ffmpeg' failed
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 526, in probe
    codec, bitrate = await loop.run_in_executor(None, lambda: probefunc(source, executable))
  File "C:\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 526, in <lambda>
    codec, bitrate = await loop.run_in_executor(None, lambda: probefunc(source, executable))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 548, in _probe_codec_native
    output = subprocess.check_output(args, timeout=20)
  File "C:\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python39\lib\subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Python39\lib\subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python39\lib\subprocess.py", line 1510, in _communicate
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_streams', '-select_streams', 'a:0', 'https://rr5---sn-i5h7lnl6.googlevideo.com/videoplayback?expire=1671775981&ei=jfKkY4-wDvSgvdIPqZOP0A4&ip=2a02%3A8108%3A83c0%3A1097%3A51cd%3Ac75a%3A28ac%3A74bb&id=o-AK4NE4mhJNlrCEYucvpxRdDvlTtnRntvsJM3a3sp2jer&itag=251&source=youtube&requiressl=yes&mh=_o&mm=31%2C26&mn=sn-i5h7lnl6%2Csn-4g5edn6k&ms=au%2Conr&mv=m&mvi=5&pl=50&initcwndbps=2587500&spc=zIddbPxcY6BESfqoYRSzTBph_SnAMRs&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=16304969&dur=36000.061&lmt=1648950511497172&mt=1671754170&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANYBYOCO3RzAYCqqEpEz-m1GBIr9GfomfhWDQxSBuwxvAiEA8LhhbHG6gFuiUMWnebHtqAuQABFNyrBR4Tf2d9gdDgQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgTLmHMjTwWG0iWe-MleXXYFoJx13q1ZVpISNRlFzKZb8CIQCyJarY22Y1DNlnywQ_tEREk1RkycjzJh5rJwZtbHeoSg%3D%3D']' timed out after 20 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 534, in probe
    codec, bitrate = await loop.run_in_executor(None, lambda: fallback(source, executable))
  File "C:\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 534, in <lambda>
    codec, bitrate = await loop.run_in_executor(None, lambda: fallback(source, executable))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 565, in _probe_codec_fallback
    out, _ = proc.communicate(timeout=20)
  File "C:\Python39\lib\subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python39\lib\subprocess.py", line 1510, in _communicate
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['ffmpeg', '-hide_banner', '-i', 'https://rr5---sn-i5h7lnl6.googlevideo.com/videoplayback?expire=1671775981&ei=jfKkY4-wDvSgvdIPqZOP0A4&ip=2a02%3A8108%3A83c0%3A1097%3A51cd%3Ac75a%3A28ac%3A74bb&id=o-AK4NE4mhJNlrCEYucvpxRdDvlTtnRntvsJM3a3sp2jer&itag=251&source=youtube&requiressl=yes&mh=_o&mm=31%2C26&mn=sn-i5h7lnl6%2Csn-4g5edn6k&ms=au%2Conr&mv=m&mvi=5&pl=50&initcwndbps=2587500&spc=zIddbPxcY6BESfqoYRSzTBph_SnAMRs&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=16304969&dur=36000.061&lmt=1648950511497172&mt=1671754170&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANYBYOCO3RzAYCqqEpEz-m1GBIr9GfomfhWDQxSBuwxvAiEA8LhhbHG6gFuiUMWnebHtqAuQABFNyrBR4Tf2d9gdDgQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgTLmHMjTwWG0iWe-MleXXYFoJx13q1ZVpISNRlFzKZb8CIQCyJarY22Y1DNlnywQ_tEREk1RkycjzJh5rJwZtbHeoSg%3D%3D']' timed out after 20 seconds
INFO 12/23/202201:14:05 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 12/23/202201:14:05 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202201:14:05 AM logging in using static token
INFO 12/23/202201:14:06 AM Shard ID None has connected to Gateway (Session ID: 2a03de5f0d2f63f22a29dd3fb9b87dab).
INFO 12/23/202201:14:08 AM Logged on as "Der Volksempfänger#5892"
INFO 12/23/202201:14:15 AM Connecting to voice...
INFO 12/23/202201:14:15 AM Starting voice handshake... (connection attempt 1)
INFO 12/23/202201:14:15 AM Voice handshake complete. Endpoint found frankfurt487.discord.media
INFO 12/23/202201:14:16 AM New Instance opened at "Test Discord"
INFO 12/23/202201:14:16 AM "Test Discord": Request "5 second video"
INFO 12/23/202201:14:18 AM "Test Discord": Request "b'5 Second Video: Watch the Milky Way Rise'" took 1s!
INFO 12/23/202201:14:26 AM 1
ERROR 12/23/202201:14:26 AM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 90, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 103, in song_complete
    file = random.choice(os.listdir(projectDir + "ads/"))
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\revol\\Documents\\Projects\\Python\\ve-pyads/'
INFO 12/23/202201:14:26 AM ffmpeg process 17520 successfully terminated with return code of 0.
INFO 12/23/202201:15:01 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 12/23/202201:15:02 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202201:15:02 AM logging in using static token
INFO 12/23/202201:15:03 AM Shard ID None has connected to Gateway (Session ID: 1278b38d77d50c762375786240f488dd).
INFO 12/23/202201:15:05 AM Logged on as "Der Volksempfänger#5892"
INFO 12/23/202201:15:07 AM Connecting to voice...
INFO 12/23/202201:15:07 AM Starting voice handshake... (connection attempt 1)
INFO 12/23/202201:15:07 AM Voice handshake complete. Endpoint found frankfurt487.discord.media
INFO 12/23/202201:15:08 AM New Instance opened at "Test Discord"
INFO 12/23/202201:15:08 AM "Test Discord": Request "5 second video"
INFO 12/23/202201:15:09 AM "Test Discord": Request "b'The Joota Chor Chapter ft. @5seconds, Karan Tacker & Avinash Tiwary | Khakee : The Bihar Chapter'" took 1s!
INFO 12/23/202201:15:34 AM 1
INFO 12/23/202201:15:34 AM "Test Discord": Playing ad: LEGO Stuka (192kbit_AAC).mp3
ERROR 12/23/202201:15:34 AM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 90, in <lambda>
    self.playing = True
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 105, in song_complete
    file = random.choice(os.listdir(projectDir + "\\\\ads"))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\voice_client.py", line 600, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
INFO 12/23/202201:15:34 AM ffmpeg process 11560 has not terminated. Waiting to terminate...
INFO 12/23/202201:15:34 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 12/23/202201:15:34 AM ffmpeg process 11560 should have terminated with a return code of 1.
INFO 12/23/202201:15:34 AM ffmpeg process 18324 successfully terminated with return code of 1.
INFO 12/23/202201:15:38 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202201:15:38 AM logging in using static token
INFO 12/23/202201:15:39 AM Shard ID None has connected to Gateway (Session ID: b9b42fe5ea8363448fdbfcb23c644a3f).
INFO 12/23/202201:15:41 AM Connecting to voice...
INFO 12/23/202201:15:41 AM Starting voice handshake... (connection attempt 1)
INFO 12/23/202201:15:41 AM Voice handshake complete. Endpoint found frankfurt487.discord.media
INFO 12/23/202201:15:41 AM Logged on as "Der Volksempfänger#5892"
INFO 12/23/202201:15:41 AM New Instance opened at "Test Discord"
INFO 12/23/202201:15:41 AM "Test Discord": Request "https://youtu.be/QC8iQqtG0hg"
INFO 12/23/202201:15:42 AM "Test Discord": Request "b'5 Second Video: Watch the Milky Way Rise'" took 0s!
INFO 12/23/202201:15:50 AM 1
INFO 12/23/202201:15:50 AM "Test Discord": Playing ad: gasleck (192kbit_AAC).mp3
INFO 12/23/202201:15:50 AM ffmpeg process 9712 successfully terminated with return code of 0.
WARNING 12/23/202201:15:50 AM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 12/23/202201:15:50 AM ffmpeg process 19888 successfully terminated with return code of 1.
INFO 12/23/202201:17:48 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 12/23/202201:17:49 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202201:17:49 AM logging in using static token
INFO 12/23/202201:17:50 AM Shard ID None has connected to Gateway (Session ID: 5fb599b8f8e6992cff603a3cdf668d80).
INFO 12/23/202201:17:52 AM Connecting to voice...
INFO 12/23/202201:17:52 AM Starting voice handshake... (connection attempt 1)
INFO 12/23/202201:17:52 AM Voice handshake complete. Endpoint found frankfurt487.discord.media
INFO 12/23/202201:17:52 AM Logged on as "Der Volksempfänger#5892"
INFO 12/23/202201:17:52 AM New Instance opened at "Test Discord"
INFO 12/23/202201:17:52 AM "Test Discord": Request "https://youtu.be/QC8iQqtG0hg"
INFO 12/23/202201:17:53 AM "Test Discord": Request "b'5 Second Video: Watch the Milky Way Rise'" took 0s!
INFO 12/23/202201:18:01 AM 0
WARNING 12/23/202201:18:01 AM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 12/23/202201:18:01 AM ffmpeg process 6276 successfully terminated with return code of 0.
INFO 12/23/202201:18:08 AM "Test Discord": Request "https://youtu.be/QC8iQqtG0hg"
INFO 12/23/202201:18:09 AM "Test Discord": Request "b'5 Second Video: Watch the Milky Way Rise'" took 0s!
INFO 12/23/202201:18:17 AM 0
WARNING 12/23/202201:18:17 AM "Test Discord": Something messed up: position >= size: 2 >= 2
INFO 12/23/202201:18:17 AM ffmpeg process 20404 successfully terminated with return code of 0.
INFO 12/23/202201:18:21 AM "Test Discord": Request "https://youtu.be/QC8iQqtG0hg"
INFO 12/23/202201:18:22 AM "Test Discord": Request "b'5 Second Video: Watch the Milky Way Rise'" took 0s!
INFO 12/23/202201:18:30 AM 0
WARNING 12/23/202201:18:30 AM "Test Discord": Something messed up: position >= size: 3 >= 3
INFO 12/23/202201:18:30 AM ffmpeg process 21216 successfully terminated with return code of 0.
INFO 12/23/202201:18:34 AM "Test Discord": Request "https://youtu.be/QC8iQqtG0hg"
INFO 12/23/202201:18:34 AM "Test Discord": Request "b'5 Second Video: Watch the Milky Way Rise'" took 0s!
INFO 12/23/202201:18:42 AM 0
WARNING 12/23/202201:18:42 AM "Test Discord": Something messed up: position >= size: 4 >= 4
INFO 12/23/202201:18:42 AM ffmpeg process 21236 successfully terminated with return code of 0.
INFO 12/23/202201:18:46 AM "Test Discord": Request "https://youtu.be/QC8iQqtG0hg"
INFO 12/23/202201:18:47 AM "Test Discord": Request "b'5 Second Video: Watch the Milky Way Rise'" took 0s!
INFO 12/23/202201:18:54 AM 1
INFO 12/23/202201:18:55 AM "Test Discord": Playing ad: gasleck (192kbit_AAC).mp3
INFO 12/23/202201:18:55 AM ffmpeg process 11096 successfully terminated with return code of 0.
WARNING 12/23/202201:18:55 AM "Test Discord": Something messed up: position >= size: 5 >= 5
INFO 12/23/202201:18:55 AM ffmpeg process 21260 successfully terminated with return code of 1.
INFO 12/23/202201:19:28 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 12/23/202201:19:29 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202201:19:29 AM logging in using static token
INFO 12/23/202201:19:30 AM Shard ID None has connected to Gateway (Session ID: 42c4a01c407bc9bae4a9ac49f149f187).
INFO 12/23/202201:19:31 AM Connecting to voice...
INFO 12/23/202201:19:31 AM Starting voice handshake... (connection attempt 1)
INFO 12/23/202201:19:31 AM Voice handshake complete. Endpoint found frankfurt487.discord.media
INFO 12/23/202201:19:32 AM New Instance opened at "Test Discord"
INFO 12/23/202201:19:32 AM "Test Discord": Request "https://youtu.be/QC8iQqtG0hg"
INFO 12/23/202201:19:32 AM Logged on as "Der Volksempfänger#5892"
INFO 12/23/202201:19:32 AM "Test Discord": Request "b'5 Second Video: Watch the Milky Way Rise'" took 0s!
INFO 12/23/202201:19:40 AM 0
WARNING 12/23/202201:19:40 AM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 12/23/202201:19:40 AM ffmpeg process 21212 successfully terminated with return code of 0.
INFO 12/23/202201:19:46 AM "Test Discord": Request "https://youtu.be/QC8iQqtG0hg"
INFO 12/23/202201:19:47 AM "Test Discord": Request "b'5 Second Video: Watch the Milky Way Rise'" took 0s!
INFO 12/23/202201:19:55 AM 1
INFO 12/23/202201:19:55 AM "Test Discord": Playing ad: Volksempfänger 2 (192kbit_AAC).mp3
INFO 12/23/202201:19:55 AM ffmpeg process 6200 successfully terminated with return code of 0.
INFO 12/23/202201:19:58 AM "Test Discord": Request "du riechst so gut"
INFO 12/23/202201:20:01 AM "Test Discord": Request "b"Rammstein - Du Riechst So Gut '98 (Official Video)"" took 2s!
INFO 12/23/202201:20:01 AM ffmpeg process 17316 has not terminated. Waiting to terminate...
INFO 12/23/202201:20:01 AM ffmpeg process 17316 should have terminated with a return code of 1.
INFO 12/23/202201:20:04 AM "Test Discord": Request "asche zu asche"
INFO 12/23/202201:20:06 AM "Test Discord": Request "b'Rammstein - Asche zu Asche (Official Lyric Video)'" took 2s!
ERROR 12/23/202201:20:13 AM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 108, in <lambda>
    self.client.play(discord.FFmpegPCMAudio(path), after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 121, in song_complete
    await self.music()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in music
    log.info("\"" + self.guild.name + "\": Playing position " + str(self.position) + ': ' + self.songs[
TypeError: can only concatenate str (not "bytes") to str
INFO 12/23/202201:20:13 AM ffmpeg process 18648 successfully terminated with return code of 0.
ERROR 12/23/202201:22:24 AM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 293, in on_message
    await obj.skip()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 134, in skip
    await self.music()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in music
    log.info("\"" + self.guild.name + "\": Playing position " + str(self.position) + ': ' + self.songs[
TypeError: can only concatenate str (not "bytes") to str
INFO 12/23/202201:22:37 AM 1
INFO 12/23/202201:22:37 AM "Test Discord": Playing ad: LEGO Opel Blitz (192kbit_AAC).mp3
ERROR 12/23/202201:22:37 AM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 92, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 108, in song_complete
    self.client.play(discord.FFmpegPCMAudio(path), after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\voice_client.py", line 600, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
INFO 12/23/202201:22:37 AM ffmpeg process 18196 has not terminated. Waiting to terminate...
INFO 12/23/202201:22:37 AM ffmpeg process 18196 should have terminated with a return code of 1.
INFO 12/23/202201:22:37 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 12/23/202201:22:37 AM ffmpeg process 20708 has not terminated. Waiting to terminate...
INFO 12/23/202201:22:37 AM ffmpeg process 20708 should have terminated with a return code of 1.
INFO 12/23/202201:22:38 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202201:22:38 AM logging in using static token
INFO 12/23/202201:22:38 AM Shard ID None has connected to Gateway (Session ID: f237eaf554a78c91709fe8a8a392708b).
INFO 12/23/202201:22:40 AM Logged on as "Der Volksempfänger#5892"
INFO 12/23/202201:22:43 AM Connecting to voice...
INFO 12/23/202201:22:43 AM Starting voice handshake... (connection attempt 1)
INFO 12/23/202201:22:43 AM Voice handshake complete. Endpoint found frankfurt487.discord.media
INFO 12/23/202201:22:43 AM New Instance opened at "Test Discord"
INFO 12/23/202201:22:43 AM "Test Discord": Request "asche zu asche"
INFO 12/23/202201:22:46 AM "Test Discord": Request "b'Rammstein - Asche zu Asche (Official Lyric Video)'" took 2s!
INFO 12/23/202201:22:46 AM "Test Discord": Playing position 0: https://youtu.be/_8C0Z8I-PuY b'Rammstein - Asche zu Asche (Official Lyric Video)'
INFO 12/23/202201:25:47 AM 1
INFO 12/23/202201:25:47 AM "Test Discord": Playing ad: erika perfüm (192kbit_AAC).mp3
ERROR 12/23/202201:25:47 AM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 92, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 108, in song_complete
    self.client.play(discord.FFmpegPCMAudio(path), after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\voice_client.py", line 600, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
INFO 12/23/202201:25:47 AM ffmpeg process 20984 has not terminated. Waiting to terminate...
INFO 12/23/202201:25:47 AM ffmpeg process 20984 should have terminated with a return code of 1.
INFO 12/23/202201:25:47 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 12/23/202201:25:47 AM ffmpeg process 7644 has not terminated. Waiting to terminate...
INFO 12/23/202201:25:47 AM ffmpeg process 7644 should have terminated with a return code of 1.
INFO 12/23/202201:25:47 AM Starting Volksempfänger version 2.2.1
INFO 12/23/202201:25:47 AM logging in using static token
INFO 12/23/202201:25:48 AM Shard ID None has connected to Gateway (Session ID: 53825f17b05269639a670bedf682ff0c).
INFO 12/23/202201:25:50 AM Logged on as "Der Volksempfänger#5892"
INFO 12/23/202201:25:57 AM Connecting to voice...
INFO 12/23/202201:25:57 AM Starting voice handshake... (connection attempt 1)
INFO 12/23/202201:25:57 AM Voice handshake complete. Endpoint found frankfurt487.discord.media
INFO 12/23/202201:25:58 AM New Instance opened at "Test Discord"
INFO 12/23/202201:25:58 AM "Test Discord": Request "https://youtu.be/QC8iQqtG0hg"
INFO 12/23/202201:25:58 AM "Test Discord": Request "b'5 Second Video: Watch the Milky Way Rise'" took 0s!
INFO 12/23/202201:25:59 AM "Test Discord": Playing position 0: https://youtu.be/QC8iQqtG0hg b'5 Second Video: Watch the Milky Way Rise'
INFO 12/23/202201:26:06 AM 1
INFO 12/23/202201:26:06 AM "Test Discord": Playing ad: LEGO Stuka (192kbit_AAC).mp3
INFO 12/23/202201:26:06 AM ffmpeg process 7928 successfully terminated with return code of 0.
WARNING 12/23/202201:26:18 AM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 12/23/202201:26:18 AM ffmpeg process 20700 successfully terminated with return code of 0.
INFO 12/23/202201:26:31 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/05/202303:24:11 PM Starting Volksempfänger version 2.3
INFO 01/05/202303:24:11 PM logging in using static token
INFO 01/05/202303:24:12 PM Shard ID None has connected to Gateway (Session ID: 6e7efa458b0f913dfdc15bb537e79586).
INFO 01/05/202303:24:14 PM Logged on as "Der Volksempfänger#5892"
INFO 01/05/202303:24:32 PM Starting Volksempfänger version 2.3
INFO 01/05/202303:24:32 PM logging in using static token
INFO 01/05/202303:24:33 PM Shard ID None has connected to Gateway (Session ID: fa1b9000eda776862bf5875f8ee52607).
INFO 01/05/202303:24:35 PM Logged on as "Der Volksempfänger#5892"
INFO 01/05/202303:24:36 PM Connecting to voice...
INFO 01/05/202303:24:36 PM Starting voice handshake... (connection attempt 1)
INFO 01/05/202303:24:36 PM Voice handshake complete. Endpoint found frankfurt6753.discord.media
INFO 01/05/202303:24:36 PM New Instance opened at "Groß deutsches Kaiserreich"
INFO 01/05/202303:24:36 PM "Groß deutsches Kaiserreich": Request "https://www.youtube.com/playlist?list=PLt1d3XhBT6esy_kwdXi_n3SywXEPY3okG"
ERROR 01/05/202303:24:43 PM Something messed up within the extractor.
INFO 01/05/202303:35:36 PM "Groß deutsches Kaiserreich": Request "super nuko world"
INFO 01/05/202303:35:37 PM "Groß deutsches Kaiserreich": Request "b'Yuikonnu & Ayaponzu Super Nuko World'" took 1s!
INFO 01/05/202303:35:38 PM "Groß deutsches Kaiserreich": Playing position 0: https://youtu.be/zwZ89IZG5WA b'Yuikonnu & Ayaponzu Super Nuko World'
WARNING 01/05/202303:39:19 PM "Groß deutsches Kaiserreich": Something messed up: position >= size: 1 >= 1
INFO 01/05/202303:39:19 PM ffmpeg process 15184 successfully terminated with return code of 0.
INFO 01/05/202304:20:19 PM The voice handshake is being terminated for Channel ID 943471203522318346 (Guild ID 701494988382404640)
INFO 01/05/202304:20:19 PM Starting Volksempfänger version 2.3
INFO 01/05/202304:20:19 PM logging in using static token
INFO 01/05/202304:20:20 PM Shard ID None has connected to Gateway (Session ID: be0ae657f8d2ad40ae4a4b2a2bf53f1e).
INFO 01/05/202304:20:22 PM Logged on as "Der Volksempfänger#5892"
INFO 01/05/202304:20:30 PM Connecting to voice...
INFO 01/05/202304:20:30 PM Starting voice handshake... (connection attempt 1)
INFO 01/05/202304:20:31 PM Voice handshake complete. Endpoint found frankfurt6753.discord.media
INFO 01/05/202304:20:31 PM New Instance opened at "Groß deutsches Kaiserreich"
INFO 01/05/202304:20:31 PM "Groß deutsches Kaiserreich": Request "https://www.youtube.com/playlist?list=PLt1d3XhBT6esy_kwdXi_n3SywXEPY3okG"
WARNING 01/05/202304:20:50 PM Requests: URL https://www.youtube.com/playlist?list=PLt1d3XhBT6esy_kwdXi_n3SywXEPY3okG is unavailable!
WARNING 01/05/202304:20:50 PM Requests: URL https://www.youtube.com/playlist?list=PLt1d3XhBT6esy_kwdXi_n3SywXEPY3okG is unavailable!
WARNING 01/05/202304:20:50 PM Requests: URL https://www.youtube.com/playlist?list=PLt1d3XhBT6esy_kwdXi_n3SywXEPY3okG is unavailable!
WARNING 01/05/202304:20:50 PM Requests: URL https://www.youtube.com/playlist?list=PLt1d3XhBT6esy_kwdXi_n3SywXEPY3okG is unavailable!
WARNING 01/05/202304:20:50 PM Requests: URL https://www.youtube.com/playlist?list=PLt1d3XhBT6esy_kwdXi_n3SywXEPY3okG is unavailable!
WARNING 01/05/202304:20:50 PM Requests: URL https://www.youtube.com/playlist?list=PLt1d3XhBT6esy_kwdXi_n3SywXEPY3okG is unavailable!
INFO 01/05/202304:20:50 PM "Groß deutsches Kaiserreich": Request "b'osu!memories'" took 18s!
INFO 01/05/202304:20:51 PM "Groß deutsches Kaiserreich": Playing position 0: https://www.youtube.com/playlist?list=PLt1d3XhBT6esy_kwdXi_n3SywXEPY3okG b'Hanasaku Iroha Character Song - Diamond'
INFO 01/05/202304:22:41 PM The voice handshake is being terminated for Channel ID 943471203522318346 (Guild ID 701494988382404640)
ERROR 01/05/202304:22:41 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 125, in song_complete
    await self.music()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in music
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\voice_client.py", line 600, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
INFO 01/05/202304:22:41 PM ffmpeg process 11416 has not terminated. Waiting to terminate...
INFO 01/05/202304:22:41 PM ffmpeg process 22784 has not terminated. Waiting to terminate...
INFO 01/05/202304:22:41 PM ffmpeg process 22784 should have terminated with a return code of 1.
INFO 01/06/202308:38:25 PM Starting Volksempfänger version 2.4
CRITICAL 01/06/202308:38:25 PM Bad config, shutting down
INFO 01/06/202308:38:43 PM Starting Volksempfänger version 2.4
CRITICAL 01/06/202308:38:43 PM Bad config, shutting down
INFO 01/06/202308:39:12 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:39:12 PM logging in using static token
INFO 01/06/202308:39:13 PM Shard ID None has connected to Gateway (Session ID: a41caf645dc18874322596c1343241be).
INFO 01/06/202308:39:15 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:39:34 PM Connecting to voice...
INFO 01/06/202308:39:34 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:39:34 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:39:34 PM New Instance opened at "Test Discord"
INFO 01/06/202308:39:34 PM "Test Discord": Request "alla"
INFO 01/06/202308:39:37 PM "Test Discord": Request "b'Alla'" took 2s!
INFO 01/06/202308:39:38 PM "Test Discord": Playing position 0: https://youtu.be/tbZXVoERylo b'Alla'
ERROR 01/06/202308:39:41 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 342, in on_message
    await reply(message.channel, 'settings', len(obj.songs), obj.shuffle, obj.loop, obj.position)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 353, in reply
    result = result % arg
TypeError: not enough arguments for format string
ERROR 01/06/202308:41:35 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 104, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:41:35 PM ffmpeg process 7464 has not terminated. Waiting to terminate...
INFO 01/06/202308:41:35 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202308:41:35 PM ffmpeg process 7464 should have terminated with a return code of 1.
INFO 01/06/202308:41:35 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:41:35 PM logging in using static token
INFO 01/06/202308:41:36 PM Shard ID None has connected to Gateway (Session ID: d1c0c174276e8d5b623dd7f2085adf2d).
INFO 01/06/202308:41:38 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:41:43 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:41:43 PM logging in using static token
INFO 01/06/202308:41:44 PM Shard ID None has connected to Gateway (Session ID: 5c3e375ee966a005f3074d58f6e06a41).
INFO 01/06/202308:41:46 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:41:48 PM Connecting to voice...
INFO 01/06/202308:41:48 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:41:48 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:41:49 PM New Instance opened at "Test Discord"
INFO 01/06/202308:41:49 PM "Test Discord": Request "allahu akbar"
INFO 01/06/202308:41:51 PM "Test Discord": Request "b'Funniest Allahu Akbar Vine Compilation'" took 2s!
INFO 01/06/202308:41:51 PM "Test Discord": Playing position 0: https://youtu.be/MA0WvwSUtCw b'Funniest Allahu Akbar Vine Compilation'
ERROR 01/06/202308:41:53 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 342, in on_message
    await reply(message.channel, 'settings', len(obj.songs), obj.shuffle, obj.loop, obj.position)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 354, in reply
    result = result % arg
TypeError: not enough arguments for format string
ERROR 01/06/202308:42:23 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 104, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:42:23 PM ffmpeg process 9104 has not terminated. Waiting to terminate...
INFO 01/06/202308:42:23 PM ffmpeg process 9104 should have terminated with a return code of 1.
INFO 01/06/202308:42:23 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202308:42:24 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:42:24 PM logging in using static token
INFO 01/06/202308:42:24 PM Shard ID None has connected to Gateway (Session ID: 36df8dfc27d0fc3868a2c7a5c1be6602).
INFO 01/06/202308:42:27 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:42:30 PM Connecting to voice...
INFO 01/06/202308:42:30 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:42:30 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:42:30 PM New Instance opened at "Test Discord"
INFO 01/06/202308:42:30 PM "Test Discord": Request "aram"
INFO 01/06/202308:42:32 PM "Test Discord": Request "b'Aramsamsam - Singen, Tanzen und Bewegen || Kinderlieder'" took 2s!
INFO 01/06/202308:42:33 PM "Test Discord": Playing position 0: https://youtu.be/gwA9GfYIYus b'Aramsamsam - Singen, Tanzen und Bewegen || Kinderlieder'
ERROR 01/06/202308:42:35 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 342, in on_message
    await reply(message.channel, 'settings', len(obj.songs), obj.shuffle, obj.loop, obj.position)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 354, in reply
    result = result % arg
TypeError: not enough arguments for format string
ERROR 01/06/202308:42:57 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 104, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:42:57 PM ffmpeg process 25892 has not terminated. Waiting to terminate...
INFO 01/06/202308:42:57 PM ffmpeg process 25892 should have terminated with a return code of 1.
INFO 01/06/202308:42:57 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202308:42:58 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:42:58 PM logging in using static token
INFO 01/06/202308:42:59 PM Shard ID None has connected to Gateway (Session ID: b32507e17f520324341104b4f9e54045).
INFO 01/06/202308:43:01 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:43:04 PM Connecting to voice...
INFO 01/06/202308:43:04 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:43:04 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:43:04 PM New Instance opened at "Test Discord"
INFO 01/06/202308:43:04 PM "Test Discord": Request "ararf"
INFO 01/06/202308:43:07 PM "Test Discord": Request "b'AR.GRAFFITI #4 - LAD PLA KAO 50 ( ARARF X PAKORN)'" took 2s!
INFO 01/06/202308:43:08 PM "Test Discord": Playing position 0: https://youtu.be/dtCJLyeBHIo b'AR.GRAFFITI #4 - LAD PLA KAO 50 ( ARARF X PAKORN)'
ERROR 01/06/202308:43:09 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 342, in on_message
    await reply(message.channel, 'settings', len(obj.songs), obj.shuffle, obj.loop, obj.position)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 354, in reply
    result = result % arg
TypeError: not enough arguments for format string
ERROR 01/06/202308:43:56 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 104, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:43:56 PM ffmpeg process 10284 has not terminated. Waiting to terminate...
INFO 01/06/202308:43:56 PM ffmpeg process 10284 should have terminated with a return code of 1.
INFO 01/06/202308:43:56 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202308:43:57 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:43:57 PM logging in using static token
INFO 01/06/202308:43:58 PM Shard ID None has connected to Gateway (Session ID: 7ac2c7f6c133d57b96521054ff38a2bc).
INFO 01/06/202308:44:00 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:44:00 PM Connecting to voice...
INFO 01/06/202308:44:00 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:44:00 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:44:01 PM New Instance opened at "Test Discord"
INFO 01/06/202308:44:01 PM "Test Discord": Request "nerf"
INFO 01/06/202308:44:04 PM "Test Discord": Request "b'NERF War: 13 Million Subscribers | NERF Superblast'" took 2s!
INFO 01/06/202308:44:05 PM "Test Discord": Playing position 0: https://youtu.be/HhG7xOC_jwE b'NERF War: 13 Million Subscribers | NERF Superblast'
ERROR 01/06/202308:44:05 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 342, in on_message
    await reply(message.channel, 'settings', len(obj.songs), obj.shuffle, obj.loop, obj.position)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 354, in reply
    result = result % arg
TypeError: not enough arguments for format string
ERROR 01/06/202308:45:38 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 104, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:45:38 PM ffmpeg process 13200 has not terminated. Waiting to terminate...
INFO 01/06/202308:45:38 PM ffmpeg process 13200 should have terminated with a return code of 1.
INFO 01/06/202308:45:38 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202308:45:38 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:45:38 PM logging in using static token
INFO 01/06/202308:45:39 PM Shard ID None has connected to Gateway (Session ID: 2196c11f8e324bf47bd7e8fee77777b8).
INFO 01/06/202308:45:41 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:45:45 PM Connecting to voice...
INFO 01/06/202308:45:45 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:45:45 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:45:45 PM New Instance opened at "Test Discord"
INFO 01/06/202308:45:45 PM "Test Discord": Request "never"
INFO 01/06/202308:45:48 PM "Test Discord": Request "b'Never (feat. O_super)'" took 2s!
INFO 01/06/202308:45:49 PM "Test Discord": Playing position 0: https://youtu.be/OSI6JJaz35I b'Never (feat. O_super)'
ERROR 01/06/202308:45:52 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 342, in on_message
    await reply(message.channel, 'settings', len(obj.songs), obj.shuffle, obj.loop, obj.position)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 352, in reply
    result = result % args
ValueError: unsupported format character '>' (0x3e) at index 52
ERROR 01/06/202308:46:10 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 104, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:46:10 PM ffmpeg process 20928 has not terminated. Waiting to terminate...
INFO 01/06/202308:46:10 PM ffmpeg process 20928 should have terminated with a return code of 1.
INFO 01/06/202308:46:10 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202308:46:11 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:46:11 PM logging in using static token
INFO 01/06/202308:46:12 PM Shard ID None has connected to Gateway (Session ID: cf48bfee8c3cf4f54d395c219fcbef89).
INFO 01/06/202308:46:14 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:46:15 PM Connecting to voice...
INFO 01/06/202308:46:15 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:46:15 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:46:16 PM New Instance opened at "Test Discord"
INFO 01/06/202308:46:16 PM "Test Discord": Request "jdsiaf"
INFO 01/06/202308:46:18 PM "Test Discord": Request "b'El Chombo   Dame Tu Cosita full Official Video  YouTube'" took 2s!
INFO 01/06/202308:46:19 PM "Test Discord": Playing position 0: https://youtu.be/0DqrIQu5wK4 b'El Chombo   Dame Tu Cosita full Official Video  YouTube'
ERROR 01/06/202308:46:21 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 342, in on_message
    await reply(message.channel, 'settings', len(obj.songs), obj.shuffle, obj.loop, obj.position)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 352, in reply
    result = result % args
ValueError: unsupported format character ',' (0x2c) at index 49
ERROR 01/06/202308:46:49 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 104, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:46:49 PM ffmpeg process 14192 has not terminated. Waiting to terminate...
INFO 01/06/202308:46:49 PM ffmpeg process 14192 should have terminated with a return code of 1.
INFO 01/06/202308:46:49 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202308:46:50 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:46:50 PM logging in using static token
INFO 01/06/202308:46:51 PM Shard ID None has connected to Gateway (Session ID: 480e4e37aa7da8b3c2885ca226a8f2b8).
INFO 01/06/202308:46:53 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:46:54 PM Connecting to voice...
INFO 01/06/202308:46:54 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:46:54 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:46:54 PM New Instance opened at "Test Discord"
INFO 01/06/202308:46:54 PM "Test Discord": Request "fdsa"
INFO 01/06/202308:46:57 PM "Test Discord": Request "b'FDSA'" took 2s!
INFO 01/06/202308:46:58 PM "Test Discord": Playing position 0: https://youtu.be/F1pLMgbJaGM b'FDSA'
ERROR 01/06/202308:47:06 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 342, in on_message
    await reply(message.channel, 'settings', len(obj.songs), obj.shuffle, obj.loop, obj.position)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 353, in reply
    result = result % args
ValueError: unsupported format character ',' (0x2c) at index 49
ERROR 01/06/202308:48:08 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 104, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:48:08 PM ffmpeg process 14380 successfully terminated with return code of 0.
INFO 01/06/202308:48:10 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202308:48:10 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:48:10 PM logging in using static token
INFO 01/06/202308:48:11 PM Shard ID None has connected to Gateway (Session ID: c2472076cfcb5c6f83aefc05bf689f1f).
INFO 01/06/202308:48:13 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:48:17 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:48:17 PM logging in using static token
INFO 01/06/202308:48:18 PM Shard ID None has connected to Gateway (Session ID: 1b1f537fe63348d2c6a654cd2972efe8).
INFO 01/06/202308:48:20 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:48:21 PM Connecting to voice...
INFO 01/06/202308:48:21 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:48:22 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:48:22 PM New Instance opened at "Test Discord"
INFO 01/06/202308:48:22 PM "Test Discord": Request "nigger"
INFO 01/06/202308:48:24 PM "Test Discord": Request "b'CLAWFINGER - Nigger (2014) // Live at Woodstock // AFM Records'" took 2s!
INFO 01/06/202308:48:25 PM "Test Discord": Playing position 0: https://youtu.be/AZLFeHdizxQ b'CLAWFINGER - Nigger (2014) // Live at Woodstock // AFM Records'
ERROR 01/06/202308:48:25 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 342, in on_message
    await reply(message.channel, 'settings', len(obj.songs), obj.shuffle, obj.loopMode, obj.position)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 352, in reply
    result = result % args
ValueError: unsupported format character ',' (0x2c) at index 49
ERROR 01/06/202308:48:40 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 104, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:48:40 PM ffmpeg process 18256 has not terminated. Waiting to terminate...
INFO 01/06/202308:48:40 PM ffmpeg process 18256 should have terminated with a return code of 1.
INFO 01/06/202308:48:40 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202308:48:41 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:48:41 PM logging in using static token
INFO 01/06/202308:48:42 PM Shard ID None has connected to Gateway (Session ID: 06dd6680ac062df187cecbf99dfde2ab).
INFO 01/06/202308:48:44 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:48:55 PM Connecting to voice...
INFO 01/06/202308:48:55 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:48:56 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:48:56 PM New Instance opened at "Test Discord"
INFO 01/06/202308:48:56 PM "Test Discord": Request "nggaga"
INFO 01/06/202308:48:58 PM "Test Discord": Request "b'BIBLE NGGAGA'" took 2s!
INFO 01/06/202308:48:59 PM "Test Discord": Playing position 0: https://youtu.be/BL0x3btJljw b'BIBLE NGGAGA'
ERROR 01/06/202308:49:00 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 342, in on_message
    await reply(message.channel, 'settings', len(obj.songs), obj.shuffle, obj.loopMode, obj.position)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 353, in reply
    result = result % args
ValueError: unsupported format character ',' (0x2c) at index 49
ERROR 01/06/202308:49:23 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 104, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:49:23 PM ffmpeg process 26340 has not terminated. Waiting to terminate...
INFO 01/06/202308:49:23 PM ffmpeg process 26340 should have terminated with a return code of 1.
INFO 01/06/202308:49:23 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202308:49:24 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:49:24 PM logging in using static token
INFO 01/06/202308:49:25 PM Shard ID None has connected to Gateway (Session ID: e5e8245c0aba85f4c320454152943a03).
INFO 01/06/202308:49:27 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:49:29 PM Connecting to voice...
INFO 01/06/202308:49:29 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:49:29 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:49:30 PM New Instance opened at "Test Discord"
INFO 01/06/202308:49:30 PM "Test Discord": Request "sdfg"
INFO 01/06/202308:49:32 PM "Test Discord": Request "b"Vlad et Maman s'amusent  lespace de jeux pour enfants"" took 2s!
INFO 01/06/202308:49:33 PM "Test Discord": Playing position 0: https://youtu.be/c18XJ-id4fQ b"Vlad et Maman s'amusent  lespace de jeux pour enfants"
ERROR 01/06/202308:49:33 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 342, in on_message
    await reply(message.channel, 'settings', len(obj.songs), obj.shuffle, obj.loopMode, obj.position)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 353, in reply
    result = result % args
ValueError: unsupported format character ' ' (0x20) at index 50
ERROR 01/06/202308:49:58 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 104, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:49:58 PM ffmpeg process 2956 has not terminated. Waiting to terminate...
INFO 01/06/202308:49:58 PM ffmpeg process 2956 should have terminated with a return code of 1.
INFO 01/06/202308:49:58 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202308:49:58 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:49:58 PM logging in using static token
INFO 01/06/202308:49:59 PM Shard ID None has connected to Gateway (Session ID: 34e2cefa86daf3a8d5bb9dd9e22e4df7).
INFO 01/06/202308:50:01 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:50:02 PM Connecting to voice...
INFO 01/06/202308:50:02 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:50:02 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:50:02 PM New Instance opened at "Test Discord"
INFO 01/06/202308:50:02 PM "Test Discord": Request "fdas"
INFO 01/06/202308:50:04 PM "Test Discord": Request "b'PAGKAKAIBA ng Addressable FDAS / Conventional FDAS | Fire Detection Alarm Systems'" took 2s!
INFO 01/06/202308:50:05 PM "Test Discord": Playing position 0: https://youtu.be/T7_FD3OOJH4 b'PAGKAKAIBA ng Addressable FDAS / Conventional FDAS | Fire Detection Alarm Systems'
INFO 01/06/202308:51:56 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202308:51:56 PM Disconnecting from voice normally, close code 1000.
ERROR 01/06/202308:51:56 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 104, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:51:56 PM ffmpeg process 29612 has not terminated. Waiting to terminate...
INFO 01/06/202308:51:56 PM ffmpeg process 29612 should have terminated with a return code of 1.
INFO 01/06/202308:52:45 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:52:45 PM logging in using static token
INFO 01/06/202308:52:46 PM Shard ID None has connected to Gateway (Session ID: 77614338391eb52be5906ee3589e6af4).
INFO 01/06/202308:52:48 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:52:51 PM Connecting to voice...
INFO 01/06/202308:52:51 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:52:52 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:52:52 PM New Instance opened at "Test Discord"
INFO 01/06/202308:52:52 PM "Test Discord": Request "2 second video"
INFO 01/06/202308:52:54 PM "Test Discord": Request "b'2 Second Video'" took 2s!
INFO 01/06/202308:52:55 PM "Test Discord": Playing position 0: https://youtu.be/UO_QuXr521I b'2 Second Video'
ERROR 01/06/202308:52:56 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 94, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 104, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:52:56 PM ffmpeg process 9480 successfully terminated with return code of 0.
INFO 01/06/202308:54:03 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202308:54:04 PM Starting Volksempfänger version 2.4
INFO 01/06/202308:54:04 PM logging in using static token
INFO 01/06/202308:54:05 PM Shard ID None has connected to Gateway (Session ID: c4c066b8c4ce3adb5412b08c14d610eb).
INFO 01/06/202308:54:07 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202308:54:11 PM Connecting to voice...
INFO 01/06/202308:54:11 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202308:54:12 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202308:54:12 PM New Instance opened at "Test Discord"
INFO 01/06/202308:54:12 PM "Test Discord": Request "2 second video"
INFO 01/06/202308:54:14 PM "Test Discord": Request "b'This Video Is 2 Seconds'" took 2s!
INFO 01/06/202308:54:15 PM "Test Discord": Playing position 0: https://youtu.be/8tulCtWsl-A b'This Video Is 2 Seconds'
ERROR 01/06/202308:54:17 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 95, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 105, in song_complete
    chance = random.randint(0, self.adChance)
AttributeError: 'MusicPlayer' object has no attribute 'adChance'
INFO 01/06/202308:54:17 PM ffmpeg process 2064 successfully terminated with return code of 0.
INFO 01/06/202309:06:02 PM Shard ID None has successfully RESUMED session c4c066b8c4ce3adb5412b08c14d610eb.
INFO 01/06/202309:06:04 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202309:14:06 PM Starting VE
INFO 01/06/202309:14:45 PM Starting VE
INFO 01/06/202309:14:45 PM Configs initialized. Version 2.4
INFO 01/06/202309:14:45 PM logging in using static token
INFO 01/06/202309:14:46 PM Shard ID None has connected to Gateway (Session ID: 26c5d4f9074cc5c9e793f35eaa85f906).
INFO 01/06/202309:14:48 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202309:14:59 PM Connecting to voice...
INFO 01/06/202309:14:59 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202309:14:59 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202309:15:00 PM New Instance opened at "Test Discord"
INFO 01/06/202309:15:00 PM "Test Discord": Request "2 second video"
INFO 01/06/202309:15:02 PM "Test Discord": Request "b'2 Second Video'" took 2s!
INFO 01/06/202309:15:03 PM "Test Discord": Playing position 0: https://youtu.be/TK4N5W22Gts b'2 Second Video'
ERROR 01/06/202309:15:05 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 93, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 103, in song_complete
    chance = random.randint(0, adChance)
  File "C:\Python39\lib\random.py", line 338, in randint
    return self.randrange(a, b+1)
TypeError: can only concatenate str (not "int") to str
INFO 01/06/202309:15:05 PM ffmpeg process 20004 successfully terminated with return code of 0.
INFO 01/06/202309:15:31 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202309:15:32 PM Starting VE
INFO 01/06/202309:15:32 PM Configs initialized. Version 2.4
INFO 01/06/202309:15:32 PM logging in using static token
INFO 01/06/202309:15:33 PM Shard ID None has connected to Gateway (Session ID: 6081cbf9e0719152d12f70a5cde091e1).
INFO 01/06/202309:15:35 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202309:15:38 PM Connecting to voice...
INFO 01/06/202309:15:38 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202309:15:39 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202309:15:39 PM New Instance opened at "Test Discord"
INFO 01/06/202309:15:39 PM "Test Discord": Request "2 second video"
INFO 01/06/202309:15:41 PM "Test Discord": Request "b'2 Second Video'" took 2s!
INFO 01/06/202309:15:43 PM "Test Discord": Playing position 0: https://youtu.be/UO_QuXr521I b'2 Second Video'
WARNING 01/06/202309:15:44 PM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 01/06/202309:15:44 PM ffmpeg process 8224 successfully terminated with return code of 0.
INFO 01/06/202309:16:30 PM "Test Discord": Changed looping mode to loop queue (1) 
INFO 01/06/202309:19:24 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202309:19:25 PM Starting VE
INFO 01/06/202309:19:25 PM Configs initialized. Version 2.4
INFO 01/06/202309:19:25 PM logging in using static token
INFO 01/06/202309:19:26 PM Shard ID None has connected to Gateway (Session ID: b51730504033e5a40f900a78af1888bb).
INFO 01/06/202309:19:28 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202309:19:33 PM Connecting to voice...
INFO 01/06/202309:19:33 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202309:19:33 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202309:19:33 PM New Instance opened at "Test Discord"
INFO 01/06/202309:19:33 PM "Test Discord": Request "never gonna give you pu"
INFO 01/06/202309:19:36 PM "Test Discord": Request "b'Rick Astley - Never Gonna Give You Up (Official Music Video)'" took 2s!
INFO 01/06/202309:19:36 PM "Test Discord": Playing position 0: https://youtu.be/dQw4w9WgXcQ b'Rick Astley - Never Gonna Give You Up (Official Music Video)'
INFO 01/06/202309:19:36 PM "Test Discord": Playing position 0: https://youtu.be/dQw4w9WgXcQ b'Rick Astley - Never Gonna Give You Up (Official Music Video)'
WARNING 01/06/202309:22:10 PM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 01/06/202309:22:10 PM ffmpeg process 2436 has not terminated. Waiting to terminate...
INFO 01/06/202309:22:10 PM ffmpeg process 2436 should have terminated with a return code of 1.
INFO 01/06/202309:22:10 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/06/202309:24:43 PM Starting VE
INFO 01/06/202309:24:43 PM Configs initialized. Version 2.4
INFO 01/06/202309:24:43 PM logging in using static token
INFO 01/06/202309:24:44 PM Shard ID None has connected to Gateway (Session ID: 143139293c2622c751ee98621d084581).
INFO 01/06/202309:24:46 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202309:29:53 PM Starting VE
INFO 01/06/202309:29:53 PM Configs initialized. Version 2.4
INFO 01/06/202309:29:53 PM logging in using static token
INFO 01/06/202309:29:54 PM Shard ID None has connected to Gateway (Session ID: 3dbcc39fc19797404219fe66982973f4).
INFO 01/06/202309:29:56 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202309:30:48 PM Connecting to voice...
INFO 01/06/202309:30:48 PM Starting voice handshake... (connection attempt 1)
INFO 01/06/202309:30:48 PM Voice handshake complete. Endpoint found frankfurt4488.discord.media
INFO 01/06/202309:30:49 PM New Instance opened at "Test Discord"
INFO 01/06/202309:30:49 PM "Test Discord": Request "https://www.youtube.com/playlist?list=PLWgGKozgFbAoYBn1G91xH3SRG2a9SbPcc"
INFO 01/06/202309:31:27 PM "Test Discord": Request "b'Lan Party fav'" took 38s!
INFO 01/06/202309:31:28 PM "Test Discord": Playing position 0: https://www.youtube.com/playlist?list=PLWgGKozgFbAoYBn1G91xH3SRG2a9SbPcc b'Plan B - Stay Too Long (Pendulum Remix) OFFICIAL VERSION'
INFO 01/06/202309:31:39 PM "Test Discord": Playing position 6: https://www.youtube.com/playlist?list=PLWgGKozgFbAoYBn1G91xH3SRG2a9SbPcc b'Bismarck'
ERROR 01/06/202309:33:14 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 276, in on_message
    if author.voice.channel is None:
AttributeError: 'NoneType' object has no attribute 'channel'
INFO 01/06/202309:34:28 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
ERROR 01/06/202309:34:29 PM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 96, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 120, in song_complete
    await self.music()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 96, in music
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\voice_client.py", line 600, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
INFO 01/06/202309:34:29 PM ffmpeg process 4104 has not terminated. Waiting to terminate...
INFO 01/06/202309:34:29 PM ffmpeg process 18468 has not terminated. Waiting to terminate...
INFO 01/06/202309:34:29 PM ffmpeg process 18468 should have terminated with a return code of 1.
INFO 01/06/202309:34:29 PM Starting VE
INFO 01/06/202309:34:29 PM Configs initialized. Version 2.4
INFO 01/06/202309:34:29 PM logging in using static token
INFO 01/06/202309:34:30 PM Shard ID None has connected to Gateway (Session ID: c81d6e31221d8369c754d344128dc910).
INFO 01/06/202309:34:32 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202309:36:51 PM Starting VE
INFO 01/06/202309:36:51 PM Configs initialized. Version 2.4
INFO 01/06/202309:36:51 PM logging in using static token
INFO 01/06/202309:36:52 PM Shard ID None has connected to Gateway (Session ID: ce45f423d642a9b4b76efc1aa585d23d).
INFO 01/06/202309:36:54 PM Logged on as "Der Volksempfänger#5892"
INFO 01/06/202309:39:34 PM Starting VE
INFO 01/06/202309:39:34 PM Configs initialized. Version 2.4
INFO 01/06/202309:39:34 PM logging in using static token
INFO 01/06/202309:39:35 PM Shard ID None has connected to Gateway (Session ID: 8f1237863f4317adceade3c0cb98c5b9).
INFO 01/06/202309:39:37 PM Logged on as "Der Volksempfänger#5892"
INFO 01/14/202309:53:24 PM Starting VE
INFO 01/14/202309:53:24 PM Configs initialized. Version 2.4
INFO 01/14/202309:53:24 PM logging in using static token
INFO 01/14/202309:53:25 PM Shard ID None has connected to Gateway (Session ID: 46abb6654b06958b8e1bf431efda36bd).
INFO 01/14/202309:53:27 PM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202312:27:37 AM Starting VE
CRITICAL 01/15/202312:27:37 AM An critical error appeared during the config setup!
CRITICAL 01/15/202312:27:37 AM [Errno 2] No such file or directory: '/lang/de-ns.json'
INFO 01/15/202312:28:18 AM Starting VE
INFO 01/15/202312:28:18 AM Configs initialized. Version 2.5
INFO 01/15/202312:28:18 AM logging in using static token
INFO 01/15/202312:28:19 AM Shard ID None has connected to Gateway (Session ID: 2ab3eca85137d6fb1a56569661888384).
INFO 01/15/202312:28:21 AM Logged on as "Der Volksempfänger#5892"
ERROR 01/15/202312:28:21 AM Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 43, in on_ready
    await self.change_presence(activity=discord.Game(name=lang_cfg['activity']))
TypeError: 'NoneType' object is not subscriptable
INFO 01/15/202312:32:37 AM Starting VE
INFO 01/15/202312:32:37 AM Configs initialized. Version 2.5
INFO 01/15/202312:32:37 AM logging in using static token
INFO 01/15/202312:32:38 AM Shard ID None has connected to Gateway (Session ID: 27ef9d1c17d8947f487e95686a9d1a63).
INFO 01/15/202312:32:40 AM Logged on as "Der Volksempfänger#5892"
ERROR 01/15/202312:32:40 AM Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 46, in on_ready
    await self.change_presence(activity=discord.Game(name=lang_cfg['activity']))
TypeError: 'NoneType' object is not subscriptable
INFO 01/15/202312:33:34 AM Starting VE
INFO 01/15/202312:33:34 AM Configs initialized. Version 2.5
INFO 01/15/202312:33:34 AM None
INFO 01/15/202312:33:34 AM logging in using static token
INFO 01/15/202312:33:35 AM Shard ID None has connected to Gateway (Session ID: 1e84e48f1a4a4cc056b3116689506339).
INFO 01/15/202312:33:37 AM Logged on as "Der Volksempfänger#5892"
ERROR 01/15/202312:33:37 AM Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 46, in on_ready
    await self.change_presence(activity=discord.Game(name=lang_cfg['activity']))
TypeError: 'NoneType' object is not subscriptable
INFO 01/15/202312:34:39 AM Starting VE
CRITICAL 01/15/202312:34:39 AM An critical error appeared during the config setup!
CRITICAL 01/15/202312:34:39 AM 'NoneType' object is not subscriptable
INFO 01/15/202312:35:19 AM Starting VE
INFO 01/15/202312:35:19 AM Configs initialized. Version 2.5
INFO 01/15/202312:35:19 AM None
INFO 01/15/202312:35:19 AM logging in using static token
INFO 01/15/202312:35:20 AM Shard ID None has connected to Gateway (Session ID: 0227942ddb0cb4939db0f65c9ae63180).
INFO 01/15/202312:35:22 AM Logged on as "Der Volksempfänger#5892"
ERROR 01/15/202312:35:22 AM Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 46, in on_ready
    await self.change_presence(activity=discord.Game(name=lang_cfg['activity']))
TypeError: 'NoneType' object is not subscriptable
INFO 01/15/202312:36:47 AM Starting VE
INFO 01/15/202312:39:37 AM Starting VE
INFO 01/15/202312:39:37 AM Configs initialized. Version 2.5
INFO 01/15/202312:39:59 AM Starting VE
INFO 01/15/202312:39:59 AM Configs initialized. Version 2.5
INFO 01/15/202312:39:59 AM {'play': 'FÃ¼hre <%s> aus', 'stop': 'Stehengeblieben!', 'resume': 'StoÃe vor in feindliches Gebiet!', 'jump': 'Skipped to %d', 'skip': 'Skipped', 'np': 'ErschieÃe: %s', 'loopq': 'Wiederhole alle Marschlieder', 'noloop': 'Schleife aufgelÃ¶st!', 'looptrack': 'Wiederhole nur dieses Marschlied', 'clear': 'Clear', 'load': 'Lade ...', 'settings': 'Der VolksempfÃ¤nger umfasst %d Lieder. Shuffle = %s, Loop = %s, Position = %d', 'shuffle': 'ZufÃ¤llige wieder gabe %s', 'rm': 'Entferne: %s', 'activity': 'Musik fÃ¼r ganz Deutschland!'}
INFO 01/15/202312:39:59 AM logging in using static token
INFO 01/15/202312:40:00 AM Shard ID None has connected to Gateway (Session ID: 455569855da743d3453451cdb8f09042).
INFO 01/15/202312:40:02 AM Logged on as "Der Volksempfänger#5892"
ERROR 01/15/202312:40:02 AM Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 44, in on_ready
    await self.change_presence(activity=discord.Game(name=lang_cfg['activity']))
NameError: name 'lang_cfg' is not defined
INFO 01/15/202312:41:49 AM Starting VE
INFO 01/15/202312:41:49 AM Configs initialized. Version 2.5
INFO 01/15/202312:41:49 AM {'play': 'FÃ¼hre <%s> aus', 'stop': 'Stehengeblieben!', 'resume': 'StoÃe vor in feindliches Gebiet!', 'jump': 'Skipped to %d', 'skip': 'Skipped', 'np': 'ErschieÃe: %s', 'loopq': 'Wiederhole alle Marschlieder', 'noloop': 'Schleife aufgelÃ¶st!', 'looptrack': 'Wiederhole nur dieses Marschlied', 'clear': 'Clear', 'load': 'Lade ...', 'settings': 'Der VolksempfÃ¤nger umfasst %d Lieder. Shuffle = %s, Loop = %s, Position = %d', 'shuffle': 'ZufÃ¤llige wieder gabe %s', 'rm': 'Entferne: %s', 'activity': 'Musik fÃ¼r ganz Deutschland!'}
INFO 01/15/202312:41:49 AM logging in using static token
INFO 01/15/202312:41:50 AM Shard ID None has connected to Gateway (Session ID: 121a042e9b52ec6d7e7646bbd6a8d30b).
INFO 01/15/202312:41:52 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202312:42:30 AM Starting VE
INFO 01/15/202312:42:30 AM Configs initialized. Version 2.5
INFO 01/15/202312:42:30 AM {'play': 'FÃ¼hre <%s> aus', 'stop': 'Stehengeblieben!', 'resume': 'StoÃe vor in feindliches Gebiet!', 'jump': 'Skipped to %d', 'skip': 'Skipped', 'np': 'ErschieÃe: %s', 'loopq': 'Wiederhole alle Marschlieder', 'noloop': 'Schleife aufgelÃ¶st!', 'looptrack': 'Wiederhole nur dieses Marschlied', 'clear': 'Clear', 'load': 'Lade ...', 'settings': 'Der VolksempfÃ¤nger umfasst %d Lieder. Shuffle = %s, Loop = %s, Position = %d', 'shuffle': 'ZufÃ¤llige wieder gabe %s', 'rm': 'Entferne: %s', 'activity': 'Musik fÃ¼r ganz Deutschland!'}
INFO 01/15/202312:42:30 AM logging in using static token
INFO 01/15/202312:42:31 AM Shard ID None has connected to Gateway (Session ID: 85506ce946a02877a96ea7007ab54d3f).
INFO 01/15/202312:42:33 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202312:42:58 AM Starting VE
INFO 01/15/202312:42:58 AM Configs initialized. Version 2.5
INFO 01/15/202312:42:58 AM logging in using static token
INFO 01/15/202312:42:59 AM Shard ID None has connected to Gateway (Session ID: 55571615adb04efc81f197fd45aee6e4).
INFO 01/15/202312:43:01 AM Logged on as "Der Volksempfänger#5892"
ERROR 01/15/202312:43:27 AM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 56, in on_message
    if cf.starts('play') or \
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_utils.py", line 12, in starts
    return self.message.startswith(prefix + key)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
INFO 01/15/202312:43:59 AM Starting VE
INFO 01/15/202312:43:59 AM Configs initialized. Version 2.5
INFO 01/15/202312:43:59 AM logging in using static token
INFO 01/15/202312:44:00 AM Shard ID None has connected to Gateway (Session ID: 8fffcc749d212f54c98f26a018a68a6e).
INFO 01/15/202312:44:02 AM Logged on as "Der Volksempfänger#5892"
ERROR 01/15/202312:44:03 AM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 56, in on_message
    if cf.starts('play') or \
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_utils.py", line 13, in starts
    return self.message.startswith(prefix + key)
NameError: name 'prefix' is not defined
INFO 01/15/202312:44:18 AM Starting VE
INFO 01/15/202312:44:18 AM Configs initialized. Version 2.5
INFO 01/15/202312:44:18 AM logging in using static token
INFO 01/15/202312:44:19 AM Shard ID None has connected to Gateway (Session ID: cfe0ec3b93028bab82d4cefb01ae2ff3).
INFO 01/15/202312:44:21 AM Logged on as "Der Volksempfänger#5892"
ERROR 01/15/202312:44:22 AM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 56, in on_message
    if cf.starts('play') or \
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_utils.py", line 14, in starts
    return self.message.startswith(prefix + key)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
INFO 01/15/202312:44:57 AM Starting VE
INFO 01/15/202312:44:57 AM Configs initialized. Version 2.5
INFO 01/15/202312:44:57 AM logging in using static token
INFO 01/15/202312:44:57 AM Shard ID None has connected to Gateway (Session ID: 7b68f1b5354c97cc6bbad8e157184115).
INFO 01/15/202312:44:59 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202312:45:39 AM Starting VE
INFO 01/15/202312:45:39 AM Configs initialized. Version 2.5
INFO 01/15/202312:45:39 AM logging in using static token
INFO 01/15/202312:45:40 AM Shard ID None has connected to Gateway (Session ID: 61c78414bdcd909e6712ad820c1bc84d).
INFO 01/15/202312:45:42 AM Logged on as "Der Volksempfänger#5892"
ERROR 01/15/202312:45:48 AM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 56, in on_message
    if cf.starts('play') or \
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_utils.py", line 14, in starts
    return self.message.startswith(prefix + key)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
INFO 01/15/202312:46:18 AM Starting VE
INFO 01/15/202312:46:18 AM Configs initialized. Version 2.5
INFO 01/15/202312:46:18 AM logging in using static token
INFO 01/15/202312:46:18 AM Shard ID None has connected to Gateway (Session ID: bf95d78a1331f5fc400e5daa3e397835).
INFO 01/15/202312:46:21 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202312:46:23 AM Connecting to voice...
INFO 01/15/202312:46:23 AM Starting voice handshake... (connection attempt 1)
INFO 01/15/202312:46:23 AM Voice handshake complete. Endpoint found frankfurt3498.discord.media
INFO 01/15/202312:46:23 AM New Instance opened at "Test Discord"
INFO 01/15/202312:48:22 AM "Test Discord": Request "nogger"
ERROR 01/15/202312:48:23 AM Something messed up within the extractor.
INFO 01/15/202312:49:35 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/15/202312:49:36 AM Starting VE
INFO 01/15/202312:49:36 AM Configs initialized. Version 2.5
INFO 01/15/202312:49:36 AM logging in using static token
INFO 01/15/202312:49:37 AM Shard ID None has connected to Gateway (Session ID: 551923a247fc1127bf3cfa02e54018c9).
INFO 01/15/202312:49:39 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202312:49:40 AM Connecting to voice...
INFO 01/15/202312:49:40 AM Starting voice handshake... (connection attempt 1)
INFO 01/15/202312:49:40 AM Voice handshake complete. Endpoint found frankfurt3498.discord.media
INFO 01/15/202312:49:40 AM New Instance opened at "Test Discord"
INFO 01/15/202312:49:52 AM "Test Discord": Request "acshe zu acsh"
ERROR 01/15/202312:49:54 AM Something messed up within the extractor.
ERROR 01/15/202312:49:54 AM 'url'
INFO 01/15/202312:55:34 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/15/202312:55:35 AM Starting VE
INFO 01/15/202312:55:35 AM Configs initialized. Version 2.5
INFO 01/15/202312:55:35 AM logging in using static token
INFO 01/15/202312:55:36 AM Shard ID None has connected to Gateway (Session ID: 71d4dec32960b4df8fb46ead4b6c6701).
INFO 01/15/202312:55:38 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202312:55:44 AM Connecting to voice...
INFO 01/15/202312:55:44 AM Starting voice handshake... (connection attempt 1)
INFO 01/15/202312:55:45 AM Voice handshake complete. Endpoint found frankfurt3498.discord.media
INFO 01/15/202312:55:45 AM New Instance opened at "Test Discord"
INFO 01/15/202312:55:49 AM "Test Discord": Request "acshe zu acshe"
ERROR 01/15/202312:55:51 AM Something messed up within the extractor.
ERROR 01/15/202312:55:51 AM 'url'
INFO 01/15/202301:05:34 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/15/202301:05:35 AM Starting VE
INFO 01/15/202301:05:35 AM Configs initialized. Version 2.5
INFO 01/15/202301:05:35 AM logging in using static token
INFO 01/15/202301:05:36 AM Shard ID None has connected to Gateway (Session ID: dce5f38301f52708c5b3f4b32eba71b7).
INFO 01/15/202301:05:38 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202301:05:41 AM Connecting to voice...
INFO 01/15/202301:05:41 AM Starting voice handshake... (connection attempt 1)
INFO 01/15/202301:05:41 AM Voice handshake complete. Endpoint found frankfurt3498.discord.media
INFO 01/15/202301:05:41 AM New Instance opened at "Test Discord"
INFO 01/15/202301:06:21 AM "Test Discord": Request "asche zu asche"
ERROR 01/15/202301:06:23 AM Something messed up within the extractor.
ERROR 01/15/202301:06:23 AM 'url'
INFO 01/15/202301:07:16 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/15/202301:07:17 AM Starting VE
INFO 01/15/202301:07:17 AM Configs initialized. Version 2.5
INFO 01/15/202301:07:17 AM logging in using static token
INFO 01/15/202301:07:18 AM Shard ID None has connected to Gateway (Session ID: 49ca4de5f6ddd759ea061f08fd989de4).
INFO 01/15/202301:07:20 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202301:07:22 AM Connecting to voice...
INFO 01/15/202301:07:22 AM Starting voice handshake... (connection attempt 1)
INFO 01/15/202301:07:22 AM Voice handshake complete. Endpoint found frankfurt3498.discord.media
INFO 01/15/202301:07:22 AM New Instance opened at "Test Discord"
INFO 01/15/202301:07:28 AM "Test Discord": Request "asche zu asche"
ERROR 01/15/202301:07:31 AM Something messed up within the extractor.
ERROR 01/15/202301:07:31 AM 'url'
INFO 01/15/202301:08:12 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/15/202301:08:13 AM Starting VE
INFO 01/15/202301:08:13 AM Configs initialized. Version 2.5
INFO 01/15/202301:08:13 AM logging in using static token
INFO 01/15/202301:08:14 AM Shard ID None has connected to Gateway (Session ID: 28035977d9d1c68829f0cb1c6182297e).
INFO 01/15/202301:08:16 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202301:08:16 AM Connecting to voice...
INFO 01/15/202301:08:16 AM Starting voice handshake... (connection attempt 1)
INFO 01/15/202301:08:17 AM Voice handshake complete. Endpoint found frankfurt3498.discord.media
INFO 01/15/202301:08:17 AM New Instance opened at "Test Discord"
INFO 01/15/202301:08:18 AM "Test Discord": Request "asche zu asch"
ERROR 01/15/202301:08:20 AM Something messed up within the extractor.
ERROR 01/15/202301:08:20 AM 'url'
INFO 01/15/202301:09:02 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/15/202301:09:02 AM Starting VE
INFO 01/15/202301:09:02 AM Configs initialized. Version 2.5
INFO 01/15/202301:09:02 AM logging in using static token
INFO 01/15/202301:09:03 AM Shard ID None has connected to Gateway (Session ID: 6162bb0b97b8512eba6c2ac317a0f855).
INFO 01/15/202301:09:05 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202301:09:11 AM Connecting to voice...
INFO 01/15/202301:09:11 AM Starting voice handshake... (connection attempt 1)
INFO 01/15/202301:09:11 AM Voice handshake complete. Endpoint found frankfurt3498.discord.media
INFO 01/15/202301:09:11 AM New Instance opened at "Test Discord"
INFO 01/15/202301:09:13 AM "Test Discord": Request "asche zu asche"
INFO 01/15/202301:09:15 AM "Test Discord": Request "b'Rammstein - Asche zu Asche (Official Lyric Video)'" took 2s!
INFO 01/15/202301:09:16 AM "Test Discord": Playing position 0: https://youtu.be/_8C0Z8I-PuY b'Rammstein - Asche zu Asche (Official Lyric Video)'
WARNING 01/15/202301:09:44 AM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 01/15/202301:09:44 AM ffmpeg process 14304 has not terminated. Waiting to terminate...
INFO 01/15/202301:09:44 AM ffmpeg process 14304 should have terminated with a return code of 1.
INFO 01/15/202301:09:44 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/15/202301:10:18 AM Starting VE
INFO 01/15/202301:10:18 AM Configs initialized. Version 2.5
INFO 01/15/202301:10:18 AM logging in using static token
INFO 01/15/202301:10:19 AM Shard ID None has connected to Gateway (Session ID: a923999110f8652437df217ce26653e8).
INFO 01/15/202301:10:21 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202301:10:24 AM Connecting to voice...
INFO 01/15/202301:10:24 AM Starting voice handshake... (connection attempt 1)
INFO 01/15/202301:10:24 AM Voice handshake complete. Endpoint found frankfurt3498.discord.media
INFO 01/15/202301:10:25 AM New Instance opened at "Test Discord"
INFO 01/15/202301:10:25 AM "Test Discord": Request "asche zu asche"
INFO 01/15/202301:10:27 AM "Test Discord": Request "b'Rammstein - Asche zu Asche (Official Lyric Video)'" took 2s!
INFO 01/15/202301:10:27 AM "Test Discord": Playing position 0: https://youtu.be/_8C0Z8I-PuY b'Rammstein - Asche zu Asche (Official Lyric Video)'
INFO 01/15/202301:14:19 AM "Test Discord": Playing ad: KZ Hotels (192kbit_AAC).mp3
INFO 01/15/202301:14:19 AM ffmpeg process 36316 successfully terminated with return code of 0.
WARNING 01/15/202301:14:50 AM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 01/15/202301:14:50 AM ffmpeg process 36236 successfully terminated with return code of 0.
INFO 01/15/202301:15:19 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/15/202301:15:20 AM Starting VE
INFO 01/15/202301:15:20 AM Configs initialized. Version 2.5
INFO 01/15/202301:15:20 AM logging in using static token
INFO 01/15/202301:15:21 AM Shard ID None has connected to Gateway (Session ID: 52e71f820b6f7b7a4c985bc3df769356).
INFO 01/15/202301:15:23 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202301:18:42 AM Starting VE
INFO 01/15/202301:18:42 AM Configs initialized. Version 2.5
INFO 01/15/202301:18:42 AM logging in using static token
INFO 01/15/202301:18:43 AM Shard ID None has connected to Gateway (Session ID: cb952ee81368e0801d337209182642c8).
INFO 01/15/202301:18:45 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202301:19:38 AM Starting VE
INFO 01/15/202301:19:38 AM Configs initialized. Version 2.5
INFO 01/15/202301:19:38 AM logging in using static token
INFO 01/15/202301:19:38 AM Shard ID None has connected to Gateway (Session ID: c3929db28206afb02b4c396b8b3b929c).
INFO 01/15/202301:19:40 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202301:19:43 AM Connecting to voice...
INFO 01/15/202301:19:43 AM Starting voice handshake... (connection attempt 1)
INFO 01/15/202301:19:44 AM Voice handshake complete. Endpoint found frankfurt3498.discord.media
INFO 01/15/202301:19:44 AM New Instance opened at "Test Discord"
INFO 01/15/202301:19:44 AM "Test Discord": Request "asche zu acshe"
INFO 01/15/202301:19:46 AM "Test Discord": Request "b'Rammstein - Asche zu Asche (Official Lyric Video)'" took 1s!
INFO 01/15/202301:19:46 AM "Test Discord": Playing position 0: https://youtu.be/_8C0Z8I-PuY b'Rammstein - Asche zu Asche (Official Lyric Video)'
WARNING 01/15/202301:20:41 AM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 01/15/202301:20:41 AM ffmpeg process 36412 has not terminated. Waiting to terminate...
INFO 01/15/202301:20:41 AM ffmpeg process 36412 should have terminated with a return code of 1.
INFO 01/15/202301:20:41 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/15/202301:20:42 AM Starting VE
INFO 01/15/202301:20:42 AM Configs initialized. Version 2.5
INFO 01/15/202301:20:42 AM logging in using static token
INFO 01/15/202301:20:42 AM Shard ID None has connected to Gateway (Session ID: 5248a210b773709cb54d30dae5ff968a).
INFO 01/15/202301:20:45 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202301:20:45 AM Connecting to voice...
INFO 01/15/202301:20:45 AM Starting voice handshake... (connection attempt 1)
INFO 01/15/202301:20:46 AM Voice handshake complete. Endpoint found frankfurt3498.discord.media
INFO 01/15/202301:20:46 AM New Instance opened at "Test Discord"
INFO 01/15/202301:20:46 AM "Test Discord": Request "asche zua assche"
INFO 01/15/202301:20:48 AM "Test Discord": Request "b'Rammstein - Asche zu Asche (Official Lyric Video)'" took 1s!
INFO 01/15/202301:20:49 AM "Test Discord": Playing position 0: https://youtu.be/_8C0Z8I-PuY b'Rammstein - Asche zu Asche (Official Lyric Video)'
INFO 01/15/202301:20:59 AM "Test Discord": Playing ad: erika perfüm (192kbit_AAC).mp3
ERROR 01/15/202301:20:59 AM Calling the after function failed.
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\player.py", line 711, in _call_after
    self.after(error)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_musicplayer.py", line 81, in <lambda>
    self.client.play(source, after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_musicplayer.py", line 99, in song_complete
    self.client.play(discord.FFmpegPCMAudio(path), after=lambda e: asyncio.run(self.song_complete()))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\voice_client.py", line 600, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
INFO 01/15/202301:20:59 AM ffmpeg process 25952 has not terminated. Waiting to terminate...
INFO 01/15/202301:20:59 AM ffmpeg process 25952 should have terminated with a return code of 1.
INFO 01/15/202301:20:59 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/15/202301:20:59 AM ffmpeg process 32204 has not terminated. Waiting to terminate...
INFO 01/15/202301:20:59 AM ffmpeg process 32204 should have terminated with a return code of 1.
INFO 01/15/202301:20:59 AM Starting VE
INFO 01/15/202301:20:59 AM Configs initialized. Version 2.5
INFO 01/15/202301:20:59 AM logging in using static token
INFO 01/15/202301:21:00 AM Shard ID None has connected to Gateway (Session ID: 390e2424edc57544f5ef805da3d69032).
INFO 01/15/202301:21:02 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202301:21:04 AM Connecting to voice...
INFO 01/15/202301:21:04 AM Starting voice handshake... (connection attempt 1)
INFO 01/15/202301:21:04 AM Voice handshake complete. Endpoint found frankfurt3498.discord.media
INFO 01/15/202301:21:04 AM New Instance opened at "Test Discord"
INFO 01/15/202301:21:04 AM "Test Discord": Request "asche zu asche"
INFO 01/15/202301:21:06 AM "Test Discord": Request "Rammstein - Asche zu Asche (Official Lyric Video)" took 2s!
INFO 01/15/202301:21:07 AM "Test Discord": Playing position 0: https://youtu.be/_8C0Z8I-PuY b'Rammstein - Asche zu Asche (Official Lyric Video)'
WARNING 01/15/202301:21:35 AM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 01/15/202301:21:35 AM ffmpeg process 34704 has not terminated. Waiting to terminate...
INFO 01/15/202301:21:35 AM ffmpeg process 34704 should have terminated with a return code of 1.
INFO 01/15/202301:21:35 AM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/15/202301:21:36 AM Starting VE
INFO 01/15/202301:21:36 AM Configs initialized. Version 2.5
INFO 01/15/202301:21:36 AM logging in using static token
INFO 01/15/202301:21:37 AM Shard ID None has connected to Gateway (Session ID: b9ad8f4c4a27d38a8a1dc993151636b4).
INFO 01/15/202301:21:39 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202301:22:02 AM Starting VE
INFO 01/15/202301:22:02 AM Configs initialized. Version 2.5
INFO 01/15/202301:22:02 AM logging in using static token
INFO 01/15/202301:22:03 AM Shard ID None has connected to Gateway (Session ID: d7bf68b32eed3a97e3a5f67ac0969287).
INFO 01/15/202301:22:05 AM Logged on as "Der Volksempfänger#5892"
INFO 01/15/202301:22:31 AM Starting VE
INFO 01/15/202301:22:31 AM Configs initialized. Version 2.5
INFO 01/15/202301:22:31 AM logging in using static token
INFO 01/15/202301:22:31 AM Shard ID None has connected to Gateway (Session ID: 75a6a765b25ff3c8b657b922c77a37da).
INFO 01/15/202301:22:33 AM Logged on as "Der Volksempfänger#5892"
INFO 01/20/202307:18:32 PM Starting MP
INFO 01/20/202307:18:32 PM Configs initialized. Version 2.5
INFO 01/20/202307:18:32 PM logging in using static token
INFO 01/20/202307:33:23 PM Starting DiscordPyMusicPlayer
INFO 01/20/202307:33:23 PM logging in using static token
INFO 01/20/202307:33:42 PM Starting DiscordPyMusicPlayer
INFO 01/20/202307:33:42 PM logging in using static token
INFO 01/20/202307:33:43 PM Shard ID None has connected to Gateway (Session ID: 0095d9923252a87b0372f54c195cfeaa).
INFO 01/20/202307:33:45 PM Logged on as "Der Volksempfänger#5892"
INFO 01/20/202307:34:38 PM Starting DiscordPyMusicPlayer
INFO 01/20/202307:34:38 PM Running version 2.5 with lang en-en
INFO 01/20/202307:34:38 PM logging in using static token
INFO 01/20/202307:34:39 PM Shard ID None has connected to Gateway (Session ID: ab51ec5a1e8ca20c4deeabbb074e89cb).
INFO 01/20/202307:34:41 PM Logged on as "Der Volksempfänger#5892"
INFO 01/20/202307:42:08 PM Starting DiscordPyMusicPlayer
INFO 01/20/202307:42:08 PM Running version 2.5 with lang en-en
INFO 01/20/202307:42:08 PM logging in using static token
INFO 01/20/202307:42:09 PM Shard ID None has connected to Gateway (Session ID: f9df11bc2723e64beabc2d79ea30feb9).
INFO 01/20/202307:42:11 PM Logged on as "Der Volksempfänger#5892"
INFO 01/20/202307:42:40 PM Connecting to voice...
INFO 01/20/202307:42:40 PM Starting voice handshake... (connection attempt 1)
INFO 01/20/202307:42:40 PM Voice handshake complete. Endpoint found frankfurt10006.discord.media
INFO 01/20/202307:42:40 PM New Instance opened at "Test Discord"
INFO 01/20/202307:42:40 PM "Test Discord": Request "https://www.youtube.com/playlist?list=PLWgGKozgFbAq6LcASZLpbjp0axPy3av4d"
INFO 01/20/202307:42:42 PM "Test Discord": Request "Tradition" took 2s!
INFO 01/20/202307:42:43 PM "Test Discord": Playing position 0: https://www.youtube.com/playlist?list=PLWgGKozgFbAq6LcASZLpbjp0axPy3av4d Reichsmetall - ARAM (Official Music Video)
WARNING 01/20/202307:45:52 PM "Test Discord": Something messed up: position >= size: 1 >= 1
INFO 01/20/202307:45:52 PM ffmpeg process 1712 successfully terminated with return code of 0.
INFO 01/20/202307:46:09 PM Disconnected from voice by force... potentially reconnecting.
INFO 01/20/202307:46:09 PM Starting voice handshake... (connection attempt 2)
WARNING 01/20/202307:47:06 PM Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO 01/20/202307:47:09 PM The voice handshake is being terminated for Channel ID 442743417362186244 (Guild ID 442743417362186240)
INFO 01/20/202307:47:09 PM Reconnect was unsuccessful, disconnecting from voice normally...
INFO 01/20/202308:12:08 PM Starting DiscordPyMusicPlayer
INFO 01/20/202308:12:08 PM Running version 2.5 with lang en-en
INFO 01/20/202308:12:08 PM logging in using static token
INFO 01/20/202308:12:09 PM Shard ID None has connected to Gateway (Session ID: ae12f342bbf2e9bb2044f56b750efbec).
INFO 01/20/202308:12:11 PM Logged on as "Der Volksempfänger#5892"
INFO 01/20/202308:12:25 PM Connecting to voice...
INFO 01/20/202308:12:25 PM Starting voice handshake... (connection attempt 1)
INFO 01/20/202308:12:25 PM Voice handshake complete. Endpoint found frankfurt10005.discord.media
INFO 01/20/202308:12:25 PM New Instance opened at "Groß deutsches Kaiserreich"
INFO 01/20/202308:12:25 PM "Groß deutsches Kaiserreich": Request "https://www.youtube.com/watch?v=Wl3DfnTffsc&list=PLWgGKozgFbAq6LcASZLpbjp0axPy3av4d&index=1"
ERROR 01/20/202308:12:25 PM Something messed up within the extractor.
ERROR 01/20/202308:12:25 PM __enter__
INFO 01/20/202308:12:45 PM The voice handshake is being terminated for Channel ID 989168134495809557 (Guild ID 701494988382404640)
INFO 01/20/202308:12:45 PM Starting DiscordPyMusicPlayer
INFO 01/20/202308:12:45 PM Running version 2.5 with lang en-en
INFO 01/20/202308:12:45 PM logging in using static token
INFO 01/20/202308:12:46 PM Shard ID None has connected to Gateway (Session ID: 64026d911fc11b440cf02ebf11284d2f).
INFO 01/20/202308:12:48 PM Logged on as "Der Volksempfänger#5892"
INFO 01/20/202308:12:49 PM Connecting to voice...
INFO 01/20/202308:12:49 PM Starting voice handshake... (connection attempt 1)
INFO 01/20/202308:12:49 PM Voice handshake complete. Endpoint found frankfurt10005.discord.media
INFO 01/20/202308:12:49 PM New Instance opened at "Groß deutsches Kaiserreich"
INFO 01/20/202308:12:49 PM "Groß deutsches Kaiserreich": Request "https://www.youtube.com/watch?v=Wl3DfnTffsc&list=PLWgGKozgFbAq6LcASZLpbjp0axPy3av4d&index=1"
ERROR 01/20/202308:12:49 PM Something messed up within the extractor.
ERROR 01/20/202308:12:49 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_musicplayer.py", line 183, in queue
    with yt_dlp.YoutubeDL as ydl:
AttributeError: __enter__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 65, in on_message
    await obj.queue(cf.get_args("q "))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_utils.py", line 29, in wrapper
    return await asyncio.to_thread(func, *args, **kwargs)
  File "C:\Python39\lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "C:\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_musicplayer.py", line 224, in queue
    log.error(e.with_traceback())
TypeError: BaseException.with_traceback() takes exactly one argument (0 given)
INFO 01/20/202308:13:48 PM The voice handshake is being terminated for Channel ID 989168134495809557 (Guild ID 701494988382404640)
INFO 01/20/202308:13:49 PM Starting DiscordPyMusicPlayer
INFO 01/20/202308:13:49 PM Running version 2.5 with lang en-en
INFO 01/20/202308:13:49 PM logging in using static token
INFO 01/20/202308:13:50 PM Shard ID None has connected to Gateway (Session ID: 6c8d6617b822b02d256a840133c85a4c).
INFO 01/20/202308:13:52 PM Logged on as "Der Volksempfänger#5892"
INFO 01/20/202308:13:52 PM Connecting to voice...
INFO 01/20/202308:13:52 PM Starting voice handshake... (connection attempt 1)
INFO 01/20/202308:13:52 PM Voice handshake complete. Endpoint found frankfurt10005.discord.media
INFO 01/20/202308:13:53 PM New Instance opened at "Groß deutsches Kaiserreich"
INFO 01/20/202308:13:53 PM "Groß deutsches Kaiserreich": Request "https://www.youtube.com/watch?v=Wl3DfnTffsc&list=PLWgGKozgFbAq6LcASZLpbjp0axPy3av4d&index=1"
ERROR 01/20/202308:13:54 PM Something messed up within the extractor.
ERROR 01/20/202308:13:54 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_musicplayer.py", line 218, in queue
    result.origin_title,
AttributeError: 'Song' object has no attribute 'origin_title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 65, in on_message
    await obj.queue(cf.get_args("q "))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_utils.py", line 29, in wrapper
    return await asyncio.to_thread(func, *args, **kwargs)
  File "C:\Python39\lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "C:\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_musicplayer.py", line 224, in queue
    log.error(e.with_traceback())
TypeError: BaseException.with_traceback() takes exactly one argument (0 given)
INFO 01/20/202308:13:59 PM The voice handshake is being terminated for Channel ID 989168134495809557 (Guild ID 701494988382404640)
INFO 01/20/202308:14:23 PM Starting DiscordPyMusicPlayer
INFO 01/20/202308:14:23 PM Running version 2.5 with lang en-en
INFO 01/20/202308:14:23 PM logging in using static token
INFO 01/20/202308:14:24 PM Shard ID None has connected to Gateway (Session ID: 889755187f732671c969e849751aaddf).
INFO 01/20/202308:14:26 PM Logged on as "Der Volksempfänger#5892"
INFO 01/20/202308:14:27 PM Connecting to voice...
INFO 01/20/202308:14:27 PM Starting voice handshake... (connection attempt 1)
INFO 01/20/202308:14:27 PM Voice handshake complete. Endpoint found frankfurt10005.discord.media
INFO 01/20/202308:14:27 PM New Instance opened at "Groß deutsches Kaiserreich"
INFO 01/20/202308:14:27 PM "Groß deutsches Kaiserreich": Request "https://www.youtube.com/watch?v=Wl3DfnTffsc&list=PLWgGKozgFbAq6LcASZLpbjp0axPy3av4d&index=1"
ERROR 01/20/202308:14:28 PM Something messed up within the extractor.
ERROR 01/20/202308:14:28 PM Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_musicplayer.py", line 218, in queue
    result.origin_title,
AttributeError: 'Song' object has no attribute 'origin_title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\revol\Documents\Projects\Python\ve-py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot.py", line 65, in on_message
    await obj.queue(cf.get_args("q "))
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_utils.py", line 29, in wrapper
    return await asyncio.to_thread(func, *args, **kwargs)
  File "C:\Python39\lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "C:\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\revol\Documents\Projects\Python\ve-py\bot_musicplayer.py", line 224, in queue
    log.error(e.with_traceback())
TypeError: BaseException.with_traceback() takes exactly one argument (0 given)
INFO 01/20/202308:14:57 PM The voice handshake is being terminated for Channel ID 989168134495809557 (Guild ID 701494988382404640)
INFO 01/20/202308:14:58 PM Starting DiscordPyMusicPlayer
INFO 01/20/202308:14:58 PM Running version 2.5 with lang en-en
INFO 01/20/202308:14:58 PM logging in using static token
INFO 01/20/202308:14:59 PM Shard ID None has connected to Gateway (Session ID: f3a4c54331daa2e408bbd4192259ae85).
INFO 01/20/202308:15:01 PM Logged on as "Der Volksempfänger#5892"
INFO 01/20/202308:15:01 PM Connecting to voice...
INFO 01/20/202308:15:01 PM Starting voice handshake... (connection attempt 1)
INFO 01/20/202308:15:01 PM Voice handshake complete. Endpoint found frankfurt10005.discord.media
INFO 01/20/202308:15:02 PM New Instance opened at "Groß deutsches Kaiserreich"
INFO 01/20/202308:15:02 PM "Groß deutsches Kaiserreich": Request "https://www.youtube.com/watch?v=Wl3DfnTffsc&list=PLWgGKozgFbAq6LcASZLpbjp0axPy3av4d&index=1"
INFO 01/20/202308:15:03 PM "Groß deutsches Kaiserreich": Request "Reichsmetall - ARAM (Official Music Video)" took 0s!
INFO 01/20/202308:15:04 PM "Groß deutsches Kaiserreich": Playing position 0: https://youtu.be/Wl3DfnTffsc Reichsmetall - ARAM (Official Music Video)
WARNING 01/20/202308:15:19 PM "Groß deutsches Kaiserreich": Something messed up: position >= size: 1 >= 1
INFO 01/20/202308:15:19 PM ffmpeg process 9576 has not terminated. Waiting to terminate...
INFO 01/20/202308:15:19 PM The voice handshake is being terminated for Channel ID 989168134495809557 (Guild ID 701494988382404640)
INFO 01/20/202308:15:19 PM ffmpeg process 9576 should have terminated with a return code of 1.
INFO 01/20/202308:20:21 PM Starting DiscordPyMusicPlayer
INFO 01/20/202308:20:21 PM Running version 2.5 with lang en-en
INFO 01/20/202308:20:21 PM logging in using static token
INFO 01/20/202308:20:22 PM Shard ID None has connected to Gateway (Session ID: 5ab8f4eadaa1f1ce046717924a61583b).
INFO 01/20/202308:20:24 PM Logged on as "Der Volksempfänger#5892"
INFO 01/20/202308:20:31 PM Connecting to voice...
INFO 01/20/202308:20:31 PM Starting voice handshake... (connection attempt 1)
INFO 01/20/202308:20:31 PM Voice handshake complete. Endpoint found frankfurt10005.discord.media
INFO 01/20/202308:20:31 PM New Instance opened at "Groß deutsches Kaiserreich"
INFO 01/20/202308:20:31 PM "Groß deutsches Kaiserreich": Request "meine name borat"
INFO 01/20/202308:20:33 PM "Groß deutsches Kaiserreich": Request "Borat" took 1s!
INFO 01/20/202308:20:33 PM "Groß deutsches Kaiserreich": Playing position 0: https://youtu.be/G90jcaCtqkY Borat
WARNING 01/20/202308:22:03 PM "Groß deutsches Kaiserreich": Something messed up: position >= size: 1 >= 1
INFO 01/20/202308:22:03 PM ffmpeg process 31444 has not terminated. Waiting to terminate...
INFO 01/20/202308:22:03 PM ffmpeg process 31444 should have terminated with a return code of 1.
INFO 01/20/202308:22:03 PM The voice handshake is being terminated for Channel ID 989168134495809557 (Guild ID 701494988382404640)
